### ISSUE TITLE
[Bug] 创建工作流失败

### ISSUE THREAD

**Issue by Admondantes** [WeBankFinTech/DataSphereStudio#1041]
### Search before asking

- [X] I searched the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar issues.

### DSS Component

dss-web/dss-workflow

### What happened + What you expected to happen

在项目里创建工作流报错

![建工作流页面](https://user-images.githubusercontent.com/46955660/231094611-e91e1fd7-0472-4210-9f44-ba8cbcafdaa4.png)
![异常日志文件1](https://user-images.githubusercontent.com/46955660/231095950-b42aa995-b782-403b-9c11-c2f166267b58.png)
![异常日志文件2](https://user-images.githubusercontent.com/46955660/231096012-9df848e0-98f3-4c2e-9202-813dbf20461d.png)
![异常日志文件3](https://user-images.githubusercontent.com/46955660/231096050-d72d7387-4107-4c72-914b-e91f0e994dd6.png)
![异常日志文件4](https://user-images.githubusercontent.com/46955660/231096079-0e9a2e55-a606-422c-b74a-52aedd41d4d9.png)
![异常日志文件5](https://user-images.githubusercontent.com/46955660/231096116-07820b1f-bb78-4b0d-9289-71518da01353.png)
![异常日志文件6](https://user-images.githubusercontent.com/46955660/231096155-ce18a5b7-5b0f-485c-a6cb-8f0293790abe.png)

![异常日志文件7](https://user-images.githubusercontent.com/46955660/231096674-c993b28f-1987-49b9-8f96-4498e057a0ac.png)

### Relevent platform

该页面使用非标准属性“zoom”。请考虑在相关属性值中使用 calc()，或将“transform”与“transform-origin: 0 0”一同使用。 172.16.105.142:8085
Object { modules: (7) […], exts: {…}, appsRoutes: {…}, appsI18n: (8) […], requireComponent: (7) […], requireComponentVue: (7) […], microModule: false, conf: {…}, gitInfo: {…} }
 apps app.2db37c59.js:1:1395224
当前环境:production app.2db37c59.js:1:1572914
不安全的（http://）页面中包含密码栏。这可能有安全风险，会导致用户账号密码被窃取。 2 172.16.105.142:8085
某些 Cookie 滥用推荐的“SameSite“属性 2
Uncaught (in promise) Error: Warning code(警告码): 90322, Warning message(警告信息): send request to dolphinscheduler failed. Caused by: HttpClientRetryException: errCode: 10900 ,desc: The user is not logged in, please log in first, you can set a retry, message:  ,ip: hadoop ,port: 9003 ,serviceKind: dss-framework-orchestrator-server-dev.
    l http://172.16.105.142:8085/js/app.2db37c59.js:1
    S http://172.16.105.142:8085/js/app.2db37c59.js:1
app.2db37c59.js:1:3253411
Uncaught (in promise) Error: error code(错误码): 71001, error message(错误信息): CheckAndSaveContext error : errCode: 70112 ,desc: InitContextInfo error. contextIDStr : {"type":"HAWorkFlowContextID","value":"{\"instance\":null,\"backupInstance\":null,\"user\":\"hadoop\",\"workspace\":\"bdapWorkspace\",\"project\":\"BI_20230411_03_DEMO\",\"flow\":\"workFlow_0411_03\",\"contextId\":\"8-8--cs_1_devcs_1_dev7\",\"version\":\"v000001\",\"env\":\"BDAP_DEV\"}"}, workTypes : ["WORKSPACE","PROJECT","FLOW"] ,ip: hadoop ,port: 9005 ,serviceKind: dss-workflow-server-dev.
    l http://172.16.105.142:8085/js/app.2db37c59.js:1
    S http://172.16.105.142:8085/js/app.2db37c59.js:1
app.2db37c59.js:1:3253411

### Reproduction script

2023-04-11 13:17:50.129 ERROR [qtp1529639302-64] org.apache.linkis.server.restful.SpringRestfulCatchAOP 71 apply - error code(错误码): 71001, error message(错误信息): CheckAndSaveContext error : errCode: 70112 ,desc: InitContextInfo error. contextIDStr : {"type":"HAWorkFlowContextID","value":"{\"instance\":null,\"backupInstance\":null,\"user\":\"hadoop\",\"workspace\":\"bdapWorkspace\",\"project\":\"BI_20230411_03_DEMO\",\"flow\":\"workFlow_0411_03\",\"contextId\":\"8-8--cs_1_devcs_1_dev7\",\"version\":\"v000001\",\"env\":\"BDAP_DEV\"}"}, workTypes : ["WORKSPACE","PROJECT","FLOW"] ,ip: hadoop ,port: 9005 ,serviceKind: dss-workflow-server-dev. org.apache.linkis.common.exception.ErrorException: errCode: 71001 ,desc: CheckAndSaveContext error : errCode: 70112 ,desc: InitContextInfo error. contextIDStr : {"type":"HAWorkFlowContextID","value":"{\"instance\":null,\"backupInstance\":null,\"user\":\"hadoop\",\"workspace\":\"bdapWorkspace\",\"project\":\"BI_20230411_03_DEMO\",\"flow\":\"workFlow_0411_03\",\"contextId\":\"8-8--cs_1_devcs_1_dev7\",\"version\":\"v000001\",\"env\":\"BDAP_DEV\"}"}, workTypes : ["WORKSPACE","PROJECT","FLOW"] ,ip: hadoop ,port: 9005 ,serviceKind: dss-workflow-server-dev ,ip: hadoop ,port: 9005 ,serviceKind: dss-workflow-server-dev
	at org.apache.linkis.common.exception.ExceptionManager.generateException(ExceptionManager.java:53) ~[linkis-common-1.1.1.jar:1.1.1]
	at org.apache.linkis.rpc.transform.RPCConsumer$$anon$1.toObject(RPCConsumer.scala:67) ~[linkis-rpc-1.1.1.jar:1.1.1]
	at org.apache.linkis.rpc.BaseRPCSender$$anonfun$ask$1.apply(BaseRPCSender.scala:87) ~[linkis-rpc-1.1.1.jar:1.1.1]
	at org.apache.linkis.rpc.BaseRPCSender.execute(BaseRPCSender.scala:80) ~[linkis-rpc-1.1.1.jar:1.1.1]
	at org.apache.linkis.rpc.BaseRPCSender.ask(BaseRPCSender.scala:83) ~[linkis-rpc-1.1.1.jar:1.1.1]
	at com.webank.wedatasphere.dss.appconn.workflow.opertion.WorkflowRefCreationOperation.createRef(WorkflowRefCreationOperation.java:62) ~[?:?]
	at com.webank.wedatasphere.dss.appconn.workflow.opertion.WorkflowRefCreationOperation.createRef(WorkflowRefCreationOperation.java:37) ~[?:?]
	at com.webank.wedatasphere.dss.orchestrator.server.service.impl.OrchestratorServiceImpl.lambda$createOrchestrator$3(OrchestratorServiceImpl.java:116) ~[dss-framework-orchestrator-server-1.1.0.jar:?]
	at com.webank.wedatasphere.dss.orchestrator.publish.utils.OrchestrationDevelopmentOperationUtils.lambda$tryOrchestrationOperation$1(OrchestrationDevelopmentOperationUtils.java:49) ~[dss-framework-orchestrator-publish-1.1.0.jar:?]
	at com.webank.wedatasphere.dss.standard.app.development.utils.DevelopmentOperationUtils.tryDevelopmentOperation(DevelopmentOperationUtils.java:56) ~[dss-development-process-standard-1.1.0.jar:?]
	at com.webank.wedatasphere.dss.standard.app.development.utils.DevelopmentOperationUtils.tryDevelopmentOperation(DevelopmentOperationUtils.java:77) ~[dss-development-process-standard-1.1.0.jar:?]
	at com.webank.wedatasphere.dss.standard.app.development.utils.DevelopmentOperationUtils.tryDevelopmentRequestRefOperation(DevelopmentOperationUtils.java:109) ~[dss-development-process-standard-1.1.0.jar:?]
	at com.webank.wedatasphere.dss.orchestrator.publish.utils.OrchestrationDevelopmentOperationUtils.tryOrchestrationOperation(OrchestrationDevelopmentOperationUtils.java:45) ~[dss-framework-orchestrator-publish-1.1.0.jar:?]
	at com.webank.wedatasphere.dss.orchestrator.server.service.impl.OrchestratorServiceImpl.tryRefOperation(OrchestratorServiceImpl.java:159) ~[dss-framework-orchestrator-server-1.1.0.jar:?]

### Anything else

创建工作流时报错

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zinc357** [comment]
这个错误有解决方法了吗

**Comment by Admondantes** [comment]
有了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月3日(周四) 下午4:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WeBankFinTech/DataSphereStudio] [Bug] 创建工作流失败 (Issue #1041)




 
这个错误有解决方法了吗

**Comment by wushengyeyouya** [comment]
It seems like the publicservice of Linkis is not worked. please start it.

**Comment by Admondantes** [comment]
OK，I will try it,&nbsp; thank you very much@,@



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月3日(周四) 晚上9:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WeBankFinTech/DataSphereStudio] [Bug] 创建工作流失败 (Issue #1041)




 
It seems like the publicservice of Linkis is not worked. please start it.

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis, Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, kylin）
3. 提供 DataSphereStudio 二次开发服务
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")

持续为DataSphereStudio开源贡献力量

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
持续为DataSphereStudio开源贡献力量

**Comment by wang-yunpeng-wyp** [comment]
How was it resolved? My public service is running normally, "Warning code: 50032, Warning message: cannot find the matched ScheuerrAppConn with name schedules "

**Comment by wang-yunpeng-wyp** [comment]
> 有了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月3日(周四) 下午4:38 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [WeBankFinTech/DataSphereStudio] [Bug] 创建工作流失败 (Issue #1041) 这个错误有解决方法了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

May I ask, how did you solve this problem? Can you help me

**Comment by jianvsgao** [comment]
> 有了
> […](#)
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2023年8月3日(周四) 下午4:38
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [WeBankFinTech/DataSphereStudio] [Bug] 创建工作流失败 (Issue [#1041](https://github.com/WeBankFinTech/DataSphereStudio/issues/1041))
> 
> 
> 
> 
> 
> 这个错误有解决方法了吗
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

请教一下，怎么解决工作流报错问题的？？？
