### ISSUE TITLE
[Bug] Error occurs when submitting a data service api with dss1.1.2

### ISSUE THREAD

**Issue by marcomeng** [WeBankFinTech/DataSphereStudio#1107]
### Search before asking

- [X] I searched the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar issues.

### DSS Component

dss-apps/dss-apiservice

### What happened + What you expected to happen

![image](https://github.com/WeBankFinTech/DataSphereStudio/assets/8347862/4e8d0458-69ee-45df-be31-2ea02f31775d)

2023-08-18 16:13:02.976 [ERROR] [qtp788557535-1892                       ] o.a.l.s.r.SpringRestfulCatchAOP (105) [$anonfun$catchMsg$1] - operation failed(操作失
败)s org.springframework.jdbc.BadSqlGrammarException:
### Cause: java.sql.SQLSyntaxErrorException: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dss.dss_workspace_user_role.created_by' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dss.dss_workspace_user_role.created_by' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
        at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:93) ~[spring-jdbc-5.2.23.RELEASE.jar:5.2.23.RELEASE]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72) ~[spring-jdbc-5.2.23.RELEASE.jar:5.2.23.RELEASE]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-5.2.23.RELEASE.jar:5.2.23.RELEASE]

### Relevent platform

dss1.1.2
centos7

### Reproduction script

2023-08-18 16:13:02.976 [ERROR] [qtp788557535-1892                       ] o.a.l.s.r.SpringRestfulCatchAOP (105) [$anonfun$catchMsg$1] - operation failed(操作失
败)s org.springframework.jdbc.BadSqlGrammarException:
### Cause: java.sql.SQLSyntaxErrorException: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dss.dss_workspace_user_role.created_by' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dss.dss_workspace_user_role.created_by' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
        at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:93) ~[spring-jdbc-5.2.23.RELEASE.jar:5.2.23.RELEASE]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72) ~[spring-jdbc-5.2.23.RELEASE.jar:5.2.23.RELEASE]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-5.2.23.RELEASE.jar:5.2.23.RELEASE]

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by marcomeng** [comment]
fix it by execute "SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));" in mysql command.
