### ISSUE TITLE
[Bug] 1.1.2一键安装后scripts页面报错

### ISSUE THREAD

**Issue by Hoxxx** [WeBankFinTech/DataSphereStudio#1114]
### Search before asking

- [X] I searched the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar issues.

### DSS Component

dss-web/dss-scriptis

### What happened + What you expected to happen

点击网页上的Scriptis 和 左边的数据库全部报错，求解？
特别是第二个报错，在仓库里没找到dss.DBS的建表语句？
下面是linkis-ps-publicservice.log的报错信息：
```
2023-09-14 16:32:44.033 [INFO ] [qtp547428000-33                         ] o.a.l.f.v.PathValidator (131) [$anonfun$dealResponseRestful$1] [JobId-] - enter the path validator,the method is getDirFileTrees
2023-09-14 16:32:44.034 [INFO ] [qtp547428000-33                         ] o.a.l.f.v.PathValidator (133) [$anonfun$dealResponseRestful$1] [JobId-] - path check trigger is open,now check the path
2023-09-14 16:32:44.034 [INFO ] [qtp547428000-33                         ] o.a.l.f.v.PathValidator (122) [validate] [JobId-] - user:hadoop,path:file:///data/wedata/temp/linkis/hadoop
2023-09-14 16:32:44.035 [INFO ] [qtp547428000-33                         ] o.a.l.s.u.ModuleUserUtils (68) [getProxyUserEntity] [JobId-] - user hadoop proxy to null operation getDirFileTrees file:///data/wedata/temp/linkis/hadoop
2023-09-14 16:32:44.036 [INFO ] [qtp547428000-33                         ] o.a.l.f.s.FsService (95) [getFileSystem] [JobId-] - hadoop gets the file type filesystem using a total of 1 milliseconds(hadoop获取file类型的filesystem一共使用了1毫秒)
2023-09-14 16:32:44.037 [INFO ] [qtp547428000-33                         ] o.a.l.s.f.i.LocalFileSystem (262) [listPathWithError] [JobId-] - Try to list path:/data/wedata/temp/linkis/hadoop with error msg
2023-09-14 16:33:02.088 [INFO ] [qtp547428000-32                         ] o.a.l.s.u.ModuleUserUtils (68) [getProxyUserEntity] [JobId-] - user hadoop proxy to null operation get dbs
2023-09-14 16:33:02.089 [INFO ] [qtp547428000-32                         ] o.a.l.m.s.i.HiveMetaWithPermissionServiceImpl (54) [getDbsOptionalUserName] [JobId-] - admin hadoop to get all dbs 
2023-09-14 16:33:02.091 [ERROR] [qtp547428000-32                         ] o.a.l.m.r.a.DataSourceRestfulApi (68) [queryDatabaseInfo] [JobId-] - Failed to get database(获取数据库失败) org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Table 'dss.DBS' doesn't exist
### The error may exist in URL [jar:file:/data/wedata/dss_linkis_one-click_install_20230809/dss_linkis/linkis/lib/linkis-public-enhancements/linkis-ps-publicservice/linkis-metadata-1.4.0.jar!/mapper/mysql/HiveMetaDao.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT NAME         FROM DBS         GROUP BY NAME         ORDER BY NAME
### Cause: java.sql.SQLSyntaxErrorException: Table 'dss.DBS' doesn't exist
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table 'dss.DBS' doesn't exist
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239) ~[spring-jdbc-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72) ~[spring-jdbc-5.2.23.RELEASE.jar:5.2.23.RELEASE]
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91) ~[mybatis-spring-2.0.6.jar:2.0.6]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441) ~[mybatis-spring-2.0.6.jar:2.0.6]
	at com.sun.proxy.$Proxy156.selectList(Unknown Source) ~[?:?]
```

### Relevent platform

centos 7.9

### Reproduction script

[ERROR] [qtp547428000-32                         ]

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Hoxxx** [comment]
没事了，ps-public里配置文件没有应用db.sh里的配置信息

**Comment by jianvsgao** [comment]
> 没事了，ps-public里配置文件没有应用db.sh里的配置信息

我也遇到这个问题了，是怎么解决的?
