### ISSUE TITLE
azkaban单独安装时没有脚本把deploy user添加到它的账户体系中

### ISSUE THREAD

**Issue by yonger1516** [WeBankFinTech/DataSphereStudio#128]
添加项目时，dss日志：
2020-04-14 19:35:15.047 [INFO ] [qtp217679065-70                         ] c.w.w.d.a.s.a.s.AzkabanSecurityService (107) [getSession] - Get azkaban response code is 200,response: {
  "error" : "Incorrect Login. Username/Password not found."
}
2020-04-14 19:35:15.049 [ERROR] [qtp217679065-70                         ] c.w.w.d.a.s.a.s.AzkabanSecurityService (80) [login] - 获取session失败: com.webank.wedatasphere.dss.appjoint.exception.AppJointErrorException: errCode: 90041 ,desc: Get azkaban session is null : {
  "error" : "Incorrect Login. Username/Password not found."
} ,ip: hadoop1 ,port: 9004 ,serviceKind: dss-server
        at com.webank.wedatasphere.dss.appjoint.scheduler.azkaban.service.AzkabanSecurityService.lambda$getSession$1(AzkabanSecurityService.java:117) ~[dss-azkaban-scheduler-appjoint-0.7.0.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_181]
        at com.webank.wedatasphere.dss.appjoint.scheduler.azkaban.service.AzkabanSecurityService.getSession(AzkabanSecurityService.java:117) ~[dss-azkaban-schedul
er-appjoint-0.7.0.jar:?]
        at com.webank.wedatasphere.dss.appjoint.scheduler.azkaban.service.AzkabanSecurityService.login(AzkabanSecurityService.java:78) [dss-azkaban-scheduler-appj
oint-0.7.0.jar:?]
        at com.webank.wedatasphere.dss.server.function.FunctionInvoker.projectServiceAddFunction(FunctionInvoker.java:76) [dss-server-0.7.0.jar:?]
        at com.webank.wedatasphere.dss.server.service.impl.DWSProjectServiceImpl.createSchedulerProject(DWSProjectServiceImpl.java:161) [dss-server-0.7.0.jar:?]
        at com.webank.wedatasphere.dss.server.service.impl.DWSProjectServiceImpl.addProject(DWSProjectServiceImpl.java:109) [dss-server-0.7.0.jar:?]
        at com.webank.wedatasphere.dss.server.service.impl.DWSProjectServiceImpl$$FastClassBySpringCGLIB$$fe55cc96.invoke(<generated>) [dss-server-0.7.0.jar:?]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) [spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEA
SE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]

需要手动添加到azkaban中

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
持续为DataSphereStudio开源贡献力量
