### ISSUE TITLE
Dss 无法发布工程到schedulis

### ISSUE THREAD

**Issue by jkl0898** [WeBankFinTech/DataSphereStudio#140]
1. dss 版本：
dss-0.7.0
linkis-0.9.3
schedulis-0.5.0

2. 现象：
创建dss 工程并制作工作流后，发布工程， 发布工程超时。
发布状态显示“已发布”
实际schedulis 的项目工程发布不完整，无法运行

3. 相关错误日志：
2020-05-28 15:56:30.266 [ERROR] [BDP-Default-Scheduler-Thread-4          ] c.w.w.d.a.s.a.s.AzkabanSecurityService (92) [login] - 获取session失败: java.lang.NullPointerException: null
 at sun.net.util.URLUtil.urlNoFragString(URLUtil.java:50) ~[?:1.8.0_121]
 at sun.misc.URLClassPath.getLoader(URLClassPath.java:512) ~[?:1.8.0_121]
 at sun.misc.URLClassPath.getNextLoader(URLClassPath.java:484) ~[?:1.8.0_121]
 at sun.misc.URLClassPath.access$100(URLClassPath.java:65) ~[?:1.8.0_121]
 at sun.misc.URLClassPath$1.next(URLClassPath.java:266) ~[?:1.8.0_121]
 at sun.misc.URLClassPath$1.hasMoreElements(URLClassPath.java:277) ~[?:1.8.0_121]
 at java.net.URLClassLoader$3$1.run(URLClassLoader.java:601) ~[?:1.8.0_121]
 at java.net.URLClassLoader$3$1.run(URLClassLoader.java:599) ~[?:1.8.0_121]
 at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
 at java.net.URLClassLoader$3.next(URLClassLoader.java:598) ~[?:1.8.0_121]
 at java.net.URLClassLoader$3.hasMoreElements(URLClassLoader.java:623) ~[?:1.8.0_121]
 at sun.misc.CompoundEnumeration.next(CompoundEnumeration.java:45) ~[?:1.8.0_121]
 at sun.misc.CompoundEnumeration.hasMoreElements(CompoundEnumeration.java:54) ~[?:1.8.0_121]
 at org.apache.commons.logging.LogFactory.getConfigurationFile(LogFactory.java:1366) ~[commons-logging-1.2.jar:1.2]
 at org.apache.commons.logging.LogFactory.getFactory(LogFactory.java:453) ~[commons-logging-1.2.jar:1.2]
 at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655) ~[commons-logging-1.2.jar:1.2]
 at org.apache.http.conn.ssl.DefaultHostnameVerifier.<init>(DefaultHostnameVerifier.java:82) ~[httpclient-4.5.4.jar:4.5.4]
 at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:955) ~[httpclient-4.5.4.jar:4.5.4]
 at com.webank.wedatasphere.dss.appjoint.scheduler.azkaban.service.AzkabanSecurityService.getSession(AzkabanSecurityService.java:119) ~[dss-azkaban-scheduler-appjoint-0.8.0.jar:?]
 at com.webank.wedatasphere.dss.appjoint.scheduler.azkaban.service.AzkabanSecurityService.login(AzkabanSecurityS

2020-05-28 14:58:26.667 [INFO ] [qtp1125059683-32                        ] c.w.w.d.s.l.LockAspect (63) [around] - 调用方法：addRootFlow
2020-05-28 14:58:26.672 [INFO ] [qtp1125059683-32                        ] c.w.w.d.s.l.LockAspect (72) [around] - projectVersionID为：8
2020-05-28 14:58:29.947 [INFO ] [qtp1125059683-32                        ] o.r.Reflections (229) [scan] - Reflections took 170 ms to scan 16 urls, producing 260 keys and 2220 values
2020-05-28 14:58:30.024 [INFO ] [qtp1125059683-32                        ] c.w.w.d.s.l.LockAspect (93) [judge] - projectVersion不会增加
2020-05-28 15:00:36.887 [INFO ] [AsyncResolver-bootstrap-executor-0      ] c.n.d.s.r.a.ConfigClusterResolver (43) [getClusterEndpoints] - Resolving eureka endpoints via configuration
2020-05-28 15:00:42.057 [INFO ] [qtp1125059683-36                        ] c.w.w.d.s.p.PublishManager (110) [addPublishCache] - 创建一个发布job8
2020-05-28 15:00:42.065 [INFO ] [project-publish1                        ] c.w.w.d.s.p.PublishManager (96) [onPublishRunning] - 开始发布工程：8
2020-05-28 15:00:42.066 [INFO ] [project-publish-deamon1                 ] c.w.w.d.s.p.PublishSubmitJobDeamon (37) [run] - projectVersionID:8的发布守护线程启
动
2020-05-28 15:00:42.069 [INFO ] [project-publish1                        ] c.w.w.d.s.l.LockAspect (63) [around] - 调用方法：publish
2020-05-28 15:00:42.074 [INFO ] [project-publish1                        ] c.w.w.d.s.l.LockAspect (72) [around] - projectVersionID为：8
2020-05-28 15:05:36.888 [INFO ] [AsyncResolver-bootstrap-executor-0      ] c.n.d.s.r.a.ConfigClusterResolver (43) [getClusterEndpoints] - Resolving eureka endpoints via configuration
2020-05-28 15:06:30.254 [INFO ] [BDP-Default-Scheduler-Thread-6          ] c.w.w.d.a.s.a.s.AzkabanSecurityService (63) [lambda$static$0] - 开始读取用户token>文件
2020-05-28 15:06:37.307 [INFO ] [BDP-Default-Scheduler-Thread-7          ] c.w.w.d.s.p.PublishManager (65) [lambda$run$0] - cache中projectVersionID为：8状态>为：Running更新时间为：2020-05-28T15:00:42.066+0800
2020-05-28 15:10:36.890 [INFO ] [AsyncResolver-bootstrap-executo

**Comment by wushengyeyouya** [comment]
Seems like login Schedulis failed, please ensure the DSS user is exists in Schedulis.

**Comment by jkl0898** [comment]
> Seems like login Schedulis failed, please ensure the DSS user is exists in Schedulis.

Hi，thanks your replied. with the help of yangzhiyue , the reason of this problem has been found. it is a bug of schedulis, we fixed this by update a schedulis jar which supplied by yangzhiyue. ask him for the details pls.

**Comment by wushengyeyouya** [comment]
OK, That's great!
