### ISSUE TITLE
DSS任务发布成功后，通过azkaban执行，报错java.lang.IllegalArgumentException dss:0.7.0

### ISSUE THREAD

**Issue by wyh-gh** [WeBankFinTech/DataSphereStudio#233]
java.lang.IllegalArgumentException: Cannot invoke com.webank.wedatasphere.linkis.ujes.client.response.ResultSetListResult.setDirFileTrees on bean class 'class com.webank.wedatasphere.linkis.ujes.client.response.ResultSetListResult' - argument type mismatch - had objects of type "java.lang.String" but expected signature "java.util.Map"
	at org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyUtilsBean.java:2181)
	at org.apache.commons.beanutils.PropertyUtilsBean.setSimpleProperty(PropertyUtilsBean.java:2141)
	at org.apache.commons.beanutils.PropertyUtilsBean.setNestedProperty(PropertyUtilsBean.java:1948)
	at org.apache.commons.beanutils.PropertyUtilsBean.setProperty(PropertyUtilsBean.java:2054)
	at org.apache.commons.beanutils.BeanUtilsBean.setProperty(BeanUtilsBean.java:1015)
	at org.apache.commons.beanutils.BeanUtilsBean.populate(BeanUtilsBean.java:830)
	at org.apache.commons.beanutils.BeanUtils.populate(BeanUtils.java:433)
	at com.webank.wedatasphere.linkis.httpclient.dws.DWSHttpClient$$anonfun$httpResponseToResult$1.apply(DWSHttpClient.scala:67)
	at com.webank.wedatasphere.linkis.httpclient.dws.DWSHttpClient$$anonfun$httpResponseToResult$1.apply(DWSHttpClient.scala:62)
	at scala.Option.map(Option.scala:146)
	at com.webank.wedatasphere.linkis.httpclient.dws.DWSHttpClient.httpResponseToResult(DWSHttpClient.scala:62)
	at com.webank.wedatasphere.linkis.httpclient.AbstractHttpClient.responseToResult(AbstractHttpClient.scala:222)
	at com.webank.wedatasphere.linkis.httpclient.AbstractHttpClient.execute(AbstractHttpClient.scala:96)
	at com.webank.wedatasphere.linkis.httpclient.AbstractHttpClient.execute(AbstractHttpClient.scala:87)
	at com.webank.wedatasphere.linkis.ujes.client.UJESClientImpl.executeUJESJob(UJESClientImpl.scala:34)
	at com.webank.wedatasphere.linkis.ujes.client.response.JobInfoResult.getResultSetList(JobInfoResult.scala:63)
	at com.webank.wedatasphere.dss.linkis.node.execution.execution.impl.LinkisNodeExecutionImpl.getResultSize(LinkisNodeExecutionImpl.java:159)
	at com.webank.wedatasphere.dss.plugins.azkaban.linkis.jobtype.AzkabanDssJobType.run(AzkabanDssJobType.java:101)
	at azkaban.execapp.JobRunner.runJob(JobRunner.java:813)
	at azkaban.execapp.JobRunner.doRun(JobRunner.java:602)
	at azkaban.execapp.JobRunner.run(JobRunner.java:563)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyUtilsBean.java:2155)

**Comment by wyh-gh** [comment]
the same issues is already exists

**Comment by Malent** [comment]
how to solve this problem
