### ISSUE TITLE
dss新建流程时调用qualitis报405

### ISSUE THREAD

**Issue by sewenc** [WeBankFinTech/DataSphereStudio#281]
dss-server log: 
```
2021-02-09 23:26:43.735 INFO  [qtp92262027-53] com.webank.wedatasphere.project.QualitisProjectServiceImpl 127 createProjectReal - Start to add project to qualitis. url: http://qualitis.b.x:80/qualitis/outer/api/v1/project/workflow?app_id=linkis_id&nonce=62256&timestamp=1612884403734&signature=eae2ba4ab4145906b573192e8076e212, method: PUT, body: <{"project_name":"dwd","description":"dwd","username":"hadoop"},{Content-Type=[application/json]}>
2021-02-09 23:26:43.952 ERROR [qtp92262027-53] com.webank.wedatasphere.project.QualitisProjectServiceImpl 95 createProject - Failed to add project to qualitis, caused by: 405 Request method 'PUT' not supported org.springframework.web.client.HttpClientErrorException: 405 Request method 'PUT' not supported

```
dss version:  0.9.0
qualitis version: 0.8.0

**Comment by sewenc** [comment]
错误原因： 真实报错是未找到用户hadoop，然后它跳转到error页面，但error页面不支持PUT访问

**Comment by sewenc** [comment]
在qualitis中新建了hadoop后又出现另一个错误：
```
java.lang.NullPointerException: null
	at com.webank.wedatasphere.qualitis.parser.LocaleParser.replacePlaceHolderByLocale(LocaleParser.java:59) ~[main/:?]
	at com.webank.wedatasphere.qualitis.aspect.DaoAspect.replaceMessage(DaoAspect.java:160) ~[main/:?]
```
在LocaleParser类48行插入一行重新打包解决：
```
localeStr= StringUtils.isBlank(localeStr)?"zh_CN":localeStr;
```
