### ISSUE TITLE
dss集成schedulis报登录失败

### ISSUE THREAD

**Issue by sewenc** [WeBankFinTech/DataSphereStudio#285]
错误日志：
```
2021-03-05 15:16:07.044 INFO  [qtp1858315458-1000] com.webank.wedatasphere.dss.server.function.FunctionInvoker 75 projectServiceAddFunction - [addProject]securityService is exist,rootlogin...
2021-03-05 15:16:07.082 INFO  [qtp1858315458-1000] com.webank.wedatasphere.dss.appjoint.scheduler.azkaban.service.AzkabanSecurityService 107 getSession - Get azkaban response code is 200,response: {
  "error" : "Login in error."
}
2021-03-05 15:16:07.086 ERROR [qtp1858315458-1000] com.webank.wedatasphere.dss.appjoint.scheduler.azkaban.service.AzkabanSecurityService 80 login - 获取session失败: com.webank.wedatasphere.dss.appjoint.exception.AppJointErrorException: errCode: 90041 ,desc: Get azkaban session is null : {
  "error" : "Login in error."
} ,ip: dss-server-68bf5b47cd-6nlts ,port: 9004 ,serviceKind: dss-server
	at com.webank.wedatasphere.dss.appjoint.scheduler.azkaban.service.AzkabanSecurityService.lambda$getSession$1(AzkabanSecurityService.java:117) ~[dss-azkaban-scheduler-appjoint-0.9.0.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_111]
	at com.webank.wedatasphere.dss.appjoint.scheduler.azkaban.service.AzkabanSecurityService.getSession(AzkabanSecurityService.java:117) ~[dss-azkaban-scheduler-appjoint-0.9.0.jar:?]
	at com.webank.wedatasphere.dss.appjoint.scheduler.azkaban.service.AzkabanSecurityService.login(AzkabanSecurityService.java:78) [dss-azkaban-scheduler-appjoint-0.9.0.jar:?]
	at com.webank.wedatasphere.dss.server.function.FunctionInvoker.projectServiceAddFunction(FunctionInvoker.java:76) [dss-server-0.9.0.jar:?]
	at com.webank.wedatasphere.dss.server.service.impl.DSSProjectServiceImpl.createSchedulerProject(DSSProjectServiceImpl.java:162) [dss-server-0.9.0.jar:?]
	at com.webank.wedatasphere.dss.server.service.impl.DSSProjectServiceImpl.ad

```

**Comment by sewenc** [comment]
查看源码，发现dss发向schedulis这边的密码的key是password,而 schedulis这边需要的key是：userpwd,导致schedulis这边认为没有传密码
AzkabanConf：
```
public static final CommonVars<String> AZKABAN_LOGIN_PWD = CommonVars.apply("wds.dss.appjoint.scheduler.azkaban.login.passwd", "password");
```
LoginAbstractAzkabanServlet
```
  private Session createSession(final HttpServletRequest req)
          throws UserManagerException, ServletException, IOException {
    final String username = getParam(req, "username");
    String password = getParam(req, "userpwd");
...

```

**Comment by sfresurgam** [comment]
hello

**Comment by iwasjoker** [comment]
老哥，这个问题怎么解决的呢
