### ISSUE TITLE
执行hql ，hive-enginemanager 抛错hiveEntrance is not exists

### ISSUE THREAD

**Issue by ZBHdd** [WeBankFinTech/DataSphereStudio#286]
版本：
dss     0.9.0
linkis  0.9.4
hadoop 2.7.2
hive      1.2.1
spark    2.3.4
错误信息：
44011: 2021-03-09 19:11:49,841 WARN  (main) WARN AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'engineReceiver': Invocation of init method failed; nested exception is java.lang.reflect.UndeclaredThrowableException
44011: 2021-03-09 19:11:49,841 INFO  (main) INFO AnnotationConfigApplicationContext - Closing SpringClientFactory-hiveEngineManager: startup date [Tue Mar 09 19:11:43 CST 2021]; parent: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@26ae880a
44011: 2021-03-09 19:11:49-843 INFO  [main] com.netflix.util.concurrent.ShutdownEnabledTimer com.netflix.util.concurrent.ShutdownEnabledTimer.cancel(ShutdownEnabledTimer.java:67) cancel - Shutdown hook removed for: NFLoadBalancer-PingTimer-hiveEngineManager
44011: 2021-03-09 19:11:49-846 ERROR [hiveEngineEngineConsumerThread] com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer com.webank.wedatasphere.linkis.common.utils.Utils$$anonfun$tryAndError$1.apply(Utils.scala:112) apply - java.lang.InterruptedException: null
44011: 	at java.lang.Object.wait(Native Method) ~[?:1.8.0_151]
44011: 	at com.webank.wedatasphere.linkis.scheduler.queue.LoopArrayQueue.take(LoopArrayQueue.scala:160) ~[linkis-scheduler-0.9.4.jar:?]
44011: 	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer.loop(FIFOUserConsumer.scala:101) ~[linkis-scheduler-0.9.4.jar:?]
44011: 	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$run$1.apply$mcV$sp(FIFOUserConsumer.scala:74) ~[linkis-scheduler-0.9.4.jar:?]
44011: 	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$run$1.apply(FIFOUserConsumer.scala:74) ~[linkis-scheduler-0.9.4.jar:?]
44011: 	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$run$1.apply(FIFOUserConsumer.scala:74) ~[linkis-scheduler-0.9.4.jar:?]
44011: 	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48) [linkis-common-0.9.4.jar:?]
44011: 	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryAndError(Utils.scala:102) [linkis-common-0.9.4.jar:?]
44011: 	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer.run(FIFOUserConsumer.scala:74) [linkis-scheduler-0.9.4.jar:?]
44011: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
44011: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
44011: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
44011: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
44011: 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
44011: 
44011: 2021-03-09 19:11:49-846 INFO  [main] com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer com.webank.wedatasphere.linkis.common.utils.Logging$class.info(Logging.scala:42) info - hiveEngineEngineConsumer is ready to stop!
44011: 2021-03-09 19:11:49-848 INFO  [main] com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer com.webank.wedatasphere.linkis.common.utils.Logging$class.info(Logging.scala:42) info - hiveEngineEngineConsumer stopped!
44011: 2021-03-09 19:11:49-849 ERROR [hiveEngineEngineConsumerThread] com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer com.webank.wedatasphere.linkis.common.utils.Utils$$anonfun$tryAndError$1.apply(Utils.scala:112) apply - java.lang.InterruptedException: sleep interrupted
44011: 	at java.lang.Thread.sleep(Native Method) ~[?:1.8.0_151]
44011: 	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$run$2.apply$mcV$sp(FIFOUserConsumer.scala:75) ~[linkis-scheduler-0.9.4.jar:?]
44011: 	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$run$2.apply(FIFOUserConsumer.scala:75) ~[linkis-scheduler-0.9.4.jar:?]
44011: 	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer$$anonfun$run$2.apply(FIFOUserConsumer.scala:75) ~[linkis-scheduler-0.9.4.jar:?]
44011: 	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48) [linkis-common-0.9.4.jar:?]
44011: 	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryAndError(Utils.scala:102) [linkis-common-0.9.4.jar:?]
44011: 	at com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer.run(FIFOUserConsumer.scala:75) [linkis-scheduler-0.9.4.jar:?]
44011: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
44011: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
44011: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
44011: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
44011: 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
44011: 
44011: 2021-03-09 19:11:49-849 INFO  [main] com.netflix.discovery.DiscoveryClient com.netflix.discovery.DiscoveryClient.shutdown(DiscoveryClient.java:888) shutdown - Shutting down DiscoveryClient ...
44011: 2021-03-09 19:11:49-849 INFO  [hiveEngineEngineConsumerThread] com.webank.wedatasphere.linkis.scheduler.queue.fifoqueue.FIFOUserConsumer com.webank.wedatasphere.linkis.common.utils.Logging$class.info(Logging.scala:42) info - hiveEngineEngineConsumer thread stopped!
44011: 2021-03-09 19:11:52-850 INFO  [main] com.netflix.discovery.DiscoveryClient com.netflix.discovery.DiscoveryClient.unregister(DiscoveryClient.java:922) unregister - Unregistering ...
44011: 2021-03-09 19:11:52-858 INFO  [main] com.netflix.discovery.DiscoveryClient com.netflix.discovery.DiscoveryClient.unregister(DiscoveryClient.java:924) unregister - DiscoveryClient_HIVEENGINE/192.168.85.129:hiveEngine:44011 - deregister  status: 404
44011: 2021-03-09 19:11:52-865 INFO  [main] com.netflix.discovery.DiscoveryClient com.netflix.discovery.DiscoveryClient.shutdown(DiscoveryClient.java:911) shutdown - Completed shut down of DiscoveryClient
44011: 2021-03-09 19:11:52-869 INFO  [main] org.eclipse.jetty.server.session org.eclipse.jetty.server.session.HouseKeeper.stopScavenging(HouseKeeper.java:167) stopScavenging - node0 Stopped scavenging
44011: 2021-03-09 19:11:52-872 INFO  [main] org.eclipse.jetty.server.handler.ContextHandler org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:1020) doStop - Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@5751e53e{application,/,[file:///tmp/jetty-docbase.8428835087974997686.44011/],UNAVAILABLE}
44011: 2021-03-09 19:11:52,882 INFO  (main) INFO ConditionEvaluationReportLoggingListener - 
44011: 
44011: Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
44011: 2021-03-09 19:11:52,885 ERROR (main) ERROR SpringApplication - Application run failed
44011: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'engineReceiver': Invocation of init method failed; nested exception is java.lang.reflect.UndeclaredThrowableException
44011: 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:138)
44011: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:424)
44011: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1700)
44011: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:581)
44011: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503)
44011: 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
44011: 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
44011: 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
44011: 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
44011: 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
44011: 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
44011: 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
44011: 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
44011: 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
44011: 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395)
44011: 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
44011: 	at com.webank.wedatasphere.linkis.DataWorkCloudApplication.main(DataWorkCloudApplication.java:105)
44011: 	at com.webank.wedatasphere.linkis.engine.DataWorkCloudEngineApplication$.main(DataWorkCloudEngineApplication.scala:71)
44011: 	at com.webank.wedatasphere.linkis.engine.DataWorkCloudEngineApplication.main(DataWorkCloudEngineApplication.scala)
44011: Caused by: java.lang.reflect.UndeclaredThrowableException
44011: 	at com.sun.proxy.$Proxy138.receive(Unknown Source)
44011: 	at com.webank.wedatasphere.linkis.rpc.BaseRPCSender$$anonfun$send$1.apply(BaseRPCSender.scala:107)
44011: 	at com.webank.wedatasphere.linkis.rpc.BaseRPCSender$$anonfun$send$1.apply(BaseRPCSender.scala:107)
44011: 	at com.webank.wedatasphere.linkis.rpc.BaseRPCSender$$anonfun$sendIt$1.apply(BaseRPCSender.scala:101)
44011: 	at com.webank.wedatasphere.linkis.rpc.interceptor.BaseRPCInterceptorExchange.invoke(RPCInterceptorExchange.scala:32)
44011: 	at com.webank.wedatasphere.linkis.rpc.interceptor.common.CommonRPCInterceptor.intercept(CommonRPCInterceptor.scala:29)
44011: 	at com.webank.wedatasphere.linkis.rpc.interceptor.BaseRPCInterceptorChain.handle(RPCInterceptorChain.scala:35)
44011: 	at com.webank.wedatasphere.linkis.rpc.interceptor.common.RetryableRPCInterceptor$$anonfun$intercept$1.apply(RetryableRPCInterceptor.scala:53)
44011: 	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48)
44011: 	at com.webank.wedatasphere.linkis.common.utils.RetryHandler$class.retry(RetryHandler.scala:56)
44011: 	at com.webank.wedatasphere.linkis.rpc.interceptor.common.RetryableRPCInterceptor$RPCRetryHandler.retry(RetryableRPCInterceptor.scala:58)
44011: 	at com.webank.wedatasphere.linkis.rpc.interceptor.common.RetryableRPCInterceptor.intercept(RetryableRPCInterceptor.scala:53)
44011: 	at com.webank.wedatasphere.linkis.rpc.interceptor.BaseRPCInterceptorChain.handle(RPCInterceptorChain.scala:35)
44011: 	at com.webank.wedatasphere.linkis.rpc.interceptor.common.CacheableRPCInterceptor.intercept(CacheableRPCInterceptor.scala:57)
44011: 	at com.webank.wedatasphere.linkis.rpc.interceptor.BaseRPCInterceptorChain.handle(RPCInterceptorChain.scala:35)
44011: 	at com.webank.wedatasphere.linkis.rpc.interceptor.common.BroadcastRPCInterceptor.intercept(BroadcastRPCInterceptor.scala:74)
44011: 	at com.webank.wedatasphere.linkis.rpc.interceptor.BaseRPCInterceptorChain.handle(RPCInterceptorChain.scala:35)
44011: 	at com.webank.wedatasphere.linkis.rpc.BaseRPCSender.execute(BaseRPCSender.scala:79)
44011: 	at com.webank.wedatasphere.linkis.rpc.BaseRPCSender.sendIt(BaseRPCSender.scala:98)
44011: 	at com.webank.wedatasphere.linkis.rpc.BaseRPCSender.send(BaseRPCSender.scala:107)
44011: 	at com.webank.wedatasphere.linkis.engine.EngineReceiver.init(EngineReceiver.scala:83)
44011: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
44011: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
44011: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
44011: 	at java.lang.reflect.Method.invoke(Method.java:498)
44011: 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365)
44011: 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:308)
44011: 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135)
44011: 	... 18 more
44011: Caused by: DWCException{errCode=10051, desc='The instance localhost:9107 of application hiveEngineManager is not exists.', ip='localhost', port=44011, serviceKind='hiveEngine'}
44011: 	at com.webank.wedatasphere.linkis.rpc.interceptor.AbstractRPCServerLoader.getOrRefresh(RPCServerLoader.scala:59)
44011: 	at com.webank.wedatasphere.linkis.rpc.interceptor.AbstractRPCServerLoader.getServer(RPCServerLoader.scala:77)
44011: 	at com.webank.wedatasphere.linkis.rpc.sender.SpringMVCRPCSender$$anon$2$$anon$1$$anonfun$customizeLoadBalancerCommandBuilder$3.apply(SpringMVCRPCSender.scala:75)
44011: 	at com.webank.wedatasphere.linkis.rpc.sender.SpringMVCRPCSender$$anon$2$$anon$1$$anonfun$customizeLoadBalancerCommandBuilder$3.apply(SpringMVCRPCSender.scala:74)
44011: 	at scala.Option.foreach(Option.scala:257)
44011: 	at com.webank.wedatasphere.linkis.rpc.sender.SpringMVCRPCSender$$anon$2$$anon$1.customizeLoadBalancerCommandBuilder(SpringMVCRPCSender.scala:74)
44011: 	at com.webank.wedatasphere.linkis.rpc.sender.SpringMVCRPCSender$$anon$2$$anon$1.customizeLoadBalancerCommandBuilder(SpringMVCRPCSender.scala:55)
44011: 	at com.netflix.client.AbstractLoadBalancerAwareClient.buildLoadBalancerCommand(AbstractLoadBalancerAwareClient.java:132)
44011: 	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:94)
44011: 	at org.springframework.cloud.openfeign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:63)
44011: 	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97)
44011: 	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
44011: 	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
44011: 	... 46 more
44011: Caused by: java.util.concurrent.TimeoutException
44011: 	at com.webank.wedatasphere.linkis.common.utils.Utils$.aux$1(Utils.scala:199)
44011: 	at com.webank.wedatasphere.linkis.common.utils.Utils$.waitUntil(Utils.scala:204)
44011: 	at com.webank.wedatasphere.linkis.rpc.interceptor.AbstractRPCServerLoader$$anonfun$getOrRefresh$1.apply$mcV$sp(RPCServerLoader.scala:61)
44011: 	at com.webank.wedatasphere.linkis.rpc.interceptor.AbstractRPCServerLoader$$anonfun$getOrRefresh$1.apply(RPCServerLoader.scala:61)
44011: 	at com.webank.wedatasphere.linkis.rpc.interceptor.AbstractRPCServerLoader$$anonfun$getOrRefresh$1.apply(RPCServerLoader.scala:61)
44011: 	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48)
44011: 	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryThrow(Utils.scala:58)
44011: 	at com.webank.wedatasphere.linkis.rpc.interceptor.AbstractRPCServerLoader.getOrRefresh(RPCServerLoader.scala:67)
44011: 	... 58 more
44011: 2021-03-09 19:11:52-889 INFO  [Thread-41] com.netflix.loadbalancer.PollingServerListUpdater com.netflix.loadbalancer.PollingServerListUpdater$LazyHolder$2.run(PollingServerListUpdater.java:53) run - Shutting down the Executor Pool for PollingServerListUpdater
44011: [hadoop@localhost ~]$ exit
44011: 登出
44011: [root@localhost ~]# exit
44011: 登出
2021-03-09 19:11:52.931 WARN  [ForkJoinPool-1-worker-5] com.webank.wedatasphere.linkis.enginemanager.process.CommonProcessEngine 51 warn - CommonProcessEngine(port: 44011, creator: IDE, user: hadoop) has stopped with exit code Some(0)
2021-03-09 19:11:52.933 INFO  [ForkJoinPool-1-worker-5] com.webank.wedatasphere.linkis.enginemanager.process.CommonProcessEngine 42 info - CommonProcessEngine(port: 44011, creator: IDE, user: hadoop) change state Starting => Dead.
2021-03-09 19:11:53.473 ERROR [Engine-Manager-Thread-2] com.webank.wedatasphere.linkis.enginemanager.impl.EngineManagerImpl 59 error - init CommonProcessEngine(port: 44011, creator: IDE, user: hadoop) failed, now stop and delete it. com.webank.wedatasphere.linkis.enginemanager.exception.EngineManagerErrorException: errCode: 20019 ,desc: init engine failed! Unknown error, please ask admin for help. ,ip: localhost ,port: 9107 ,serviceKind: hiveEngineManager

**Comment by bigfacewo** [comment]
遇到同样的问题，好不容易搜到个相关的，没人理🤣

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
持续为DataSphereStudio开源贡献力量
