### ISSUE TITLE
DSS0.9.1 with Linkis0.9.4 not compatible with HDP3.1

### ISSUE THREAD

**Issue by lordk911** [WeBankFinTech/DataSphereStudio#311]
When I run HSQL I got ERROR:

`2021-04-25 09:44:40.044 INFO Your job is accepted,  jobID is IDE_bigtop_0 and taskID is 1. Please wait it to be scheduled
2021-04-25 09:44:40.044 INFO Your job is Scheduled. Please wait it to run.
2021-04-25 09:44:43.044 INFO Background is starting a new engine for you, it may take several seconds, please wait
2021-04-25 09:44:56.044 INFO Congratulations! Your new engine has started successfully
ClassNotFoundException: org.apache.tez.dag.api.TezConfiguration
2021-04-25 09:44:56.044 ERROR Request engine failed, possibly due to insufficient resources or background process error(请求引擎失败，可能是由于资源不足或后台进程错误)!
2021-04-25 09:44:57.044 ERROR DWCException{errCode=20010, desc='ClassNotFoundException: org.apache.tez.dag.api.TezConfiguration', ip='host-10-0-105-243', port=9108, serviceKind='hiveEntrance'}
	at com.webank.wedatasphere.linkis.entrance.execute.EngineRequester$EngineInitThread.notifyThread(EngineRequester.scala:108)
	at com.webank.wedatasphere.linkis.entrance.execute.EngineRequester$EngineInitThread.notifyThread(EngineRequester.scala:116)
	at com.webank.wedatasphere.linkis.entrance.execute.EngineRequester.reportNewEngineStatus(EngineRequester.scala:83)
	at com.webank.wedatasphere.linkis.entrance.execute.EntranceReceiver.receive(EntranceReceiver.scala:104)
	at com.webank.wedatasphere.linkis.rpc.RPCReceiveRestful$$anon$1$$anonfun$onEvent$2.apply(RPCReceiveRestful.scala:92)
	at com.webank.wedatasphere.linkis.rpc.RPCReceiveRestful$$anon$1$$anonfun$onEvent$2.apply(RPCReceiveRestful.scala:92)
	at scala.Option.fold(Option.scala:158)`

When I run sparksql I got ERROR:

`2021-04-25 09:55:51.266 INFO  [qtp1455871253-28] com.webank.wedatasphere.linkis.resourcemanager.utils.YarnUtil$ 42 info - Hadoop version is JString(3.1.1.3.1.4.0-315)
2021-04-25 09:55:51.286 ERROR [qtp1455871253-28] com.webank.wedatasphere.linkis.rpc.RPCReceiveRestful 72 apply - error code(错误码): 11006, error message(错误信息): Get the Yarn queue information exception.(获取Yarn队列信息异常). com.webank.wedatasphere.linkis.resourcemanager.exception.RMErrorException: errCode: 11006 ,desc: Get the Yarn queue information exception.(获取Yarn队列信息异常) ,ip: host-10-0-105-243 ,port: 9104 ,serviceKind: ResourceManager
`

`
Caused by: java.lang.ClassCastException: org.json4s.JsonAST$JDouble cannot be cast to org.json4s.JsonAST$JDecimal
	at com.webank.wedatasphere.linkis.resourcemanager.utils.YarnUtil$$anonfun$maxEffectiveHandle$1$1.apply(YarnUtil.scala:136) ~[linkis-resourcemanager-server-0.9.4.jar:?]
	at com.webank.wedatasphere.linkis.resourcemanager.utils.YarnUtil$$anonfun$maxEffectiveHandle$1$1.apply(YarnUtil.scala:135) ~[linkis-resourcemanager-server-0.9.4.jar:?]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.8.jar:?]
	at com.webank.wedatasphere.linkis.resourcemanager.utils.YarnUtil$.maxEffectiveHandle$1(YarnUtil.scala:135) ~[linkis-resourcemanager-server-0.9.4.jar:?]
	at com.webank.wedatasphere.linkis.resourcemanager.utils.YarnUtil$.com$webank$wedatasphere$linkis$resourcemanager$utils$YarnUtil$$getResources$1(YarnUtil.scala:203) ~[linkis-resourcemanager-server-0.9.4.jar:?]
	at com.webank.wedatasphere.linkis.resourcemanager.utils.YarnUtil$$anonfun$getQueueInfo$1.apply(YarnUtil.scala:219) ~[linkis-resourcemanager-server-0.9.4.jar:?]
	at com.webank.wedatasphere.linkis.resourcemanager.utils.YarnUtil$$anonfun$getQueueInfo$1.apply(YarnUtil.scala:219) ~[linkis-resourcemanager-server-0.9.4.jar:?]
	at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48) ~[linkis-common-0.9.4.jar:?]
	... 121 more`

**Comment by you10906** [comment]
i got the same error when i executed hsql.   
Linkis version is 0.9.4 ,  HDP version is 3.1.4
```
2021-07-15 13:35:34.035 INFO Your job is accepted,  jobID is IDE_hadoop_11 and taskID is 14. Please wait it to be scheduled
2021-07-15 13:35:34.035 INFO Your job is Scheduled. Please wait it to run.
2021-07-15 13:35:35.035 INFO Background is starting a new engine for you, it may take several seconds, please wait
2021-07-15 13:35:45.035 INFO Congratulations! Your new engine has started successfully
ClassNotFoundException: org.apache.tez.dag.api.TezConfiguration
2021-07-15 13:35:45.035 ERROR Request engine failed, possibly due to insufficient resources or background process error(请求引擎失败，可能是由于资源不足或后台进程错误)!
2021-07-15 13:35:45.035 ERROR DWCException{errCode=20010, desc='ClassNotFoundException: org.apache.tez.dag.api.TezConfiguration', ip='nn01', port=9108, serviceKind='hiveEntrance'}
	at com.webank.wedatasphere.linkis.entrance.execute.EngineRequester$EngineInitThread.notifyThread(EngineRequester.scala:108)
	at com.webank.wedatasphere.linkis.entrance.execute.EngineRequester$EngineInitThread.notifyThread(EngineRequester.scala:116)
	at com.webank.wedatasphere.linkis.entrance.execute.EngineRequester.reportNewEngineStatus(EngineRequester.scala:83)
	at com.webank.wedatasphere.linkis.entrance.execute.EntranceReceiver.receive(EntranceReceiver.scala:104)
```

**Comment by gangly** [comment]
same error  with hdp.

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
持续为DataSphereStudio开源贡献力量
