### ISSUE TITLE
Workflow node qualitis execution wrong and throws null pointer exception

### ISSUE THREAD

**Issue by chaogefeng** [WeBankFinTech/DataSphereStudio#32]
```
2019-12-12 23:04:41.706 ERROR [Engine-Scheduler-ThreadPool-2] com.webank.wedatasphere.appjoint.QualitisAppJoint 106 submit - Error! Can not submit job java.lang.NullPointerException: null
        at com.webank.wedatasphere.appjoint.QualitisNodeExecution.submit(QualitisNodeExecution.java:67) [dss-qualitis-appjoint-0.6.0.jar:?]
        at com.webank.wedatasphere.dss.appjoint.execution.core.LongTermNodeExecution.execute(LongTermNodeExecution.java:65) [dss-appjoint-core-0.6.0.jar:?]
        at com.webank.wedatasphere.dss.linkis.appjoint.entrance.execute.AppJointEntranceEngine.execute(AppJointEntranceEngine.scala:169) [linkis-appjoint-entrance-0.6.0.jar:?]
        at com.webank.wedatasphere.dss.linkis.appjoint.entrance.job.AppJointEntranceJob$$anonfun$1.apply(AppJointEntranceJob.scala:75) [linkis-appjoint-entrance-0.6.0.jar:?]
        at com.webank.wedatasphere.dss.linkis.appjoint.entrance.job.AppJointEntranceJob$$anonfun$1.apply(AppJointEntranceJob.scala:75) [linkis-appjoint-entrance-0.6.0.jar:?]
        at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:48) [linkis-common-0.9.1.jar:?]
        at com.webank.wedatasphere.dss.linkis.appjoint.entrance.job.AppJointEntranceJob.run(AppJointEntranceJob.scala:75) [linkis-appjoint-entrance-0.6.0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
```

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
持续为DataSphereStudio开源贡献力量
