### ISSUE TITLE
dss-server login first time

### ISSUE THREAD

**Issue by leiyazhen** [WeBankFinTech/DataSphereStudio#398]
when i deploy all dss componet,i login dss-web with user hadoop,and then got this error
`
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'dss_server.linkis_user' doesn't exist
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'dss_server.linkis_user' doesn't exist
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231) ~[spring-jdbc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73) ~[spring-jdbc-4.3.14.RELEASE.jar:4.3.14.RELEASE]
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73) ~[mybatis-spring-1.3.2.jar:1.3.2]
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446) ~[mybatis-spring-1.3.2.jar:1.3.2]
        at com.sun.proxy.$Proxy136.selectOne(Unknown Source) ~[?:?]
        at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166) ~[mybatis-spring-1.3.2.jar:1.3.2]
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:83) ~[mybatis-3.4.6.jar:3.4.6]
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59) ~[mybatis-3.4.6.jar:3.4.6]
        at com.sun.proxy.$Proxy169.getUserByName(Unknown Source) ~[?:?]
        at com.webank.wedatasphere.dss.application.service.impl.LinkisUserServiceImpl.getUserByName(LinkisUserServiceImpl.java:40) ~[dss-application-0.9.0.jar:?]
        at com.webank.wedatasphere.dss.application.handler.LinkisUserFirstLoginHandler.handle(LinkisUserFirstLoginHandler.java:49) ~[dss-application-0.9.0.jar:?]
        at com.webank.wedatasphere.dss.application.handler.ApplicationHandlerChain.lambda$handle$1(ApplicationHandlerChain.java:43) ~[dss-application-0.9.0.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_301]
        at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352) ~[?:1.8.0_301]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483) ~[?:1.8.0_301]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_301]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_301]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_301]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_301]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_301]
        at com.webank.wedatasphere.dss.application.handler.ApplicationHandlerChain.handle(ApplicationHandlerChain.java:43) ~[dss-application-0.9.0.jar:?]
        at com.webank.wedatasphere.dss.application.restful.ApplicationRestfulApi.getBaseInfo(ApplicationRestfulApi.java:62) ~[dss-application-0.9.0.jar:?]
        at com.webank.wedatasphere.dss.application.restful.ApplicationRestfulApi$$FastClassBySpringCGLIB$$4835b02.invoke(<generated>) ~[dss-application-0.9.0.jar:?]
`
dss_server is mysql database,in which has no table start with linkis_*.
during deploy i had source sql file in the dir db.

**Comment by wushengyeyouya** [comment]
Please install the latest version of DSS1.0.
