### ISSUE TITLE
按照1.0.0版本的单机部署文档，部署完成后，在启动linkis-cg-engineconnmanager时，报No appropriate protocol，是不是有哪些配置没有配置好？

### ISSUE THREAD

**Issue by juyonychen** [WeBankFinTech/DataSphereStudio#426]
2021-09-22 20:36:07.011 [ERROR] [main                                    ] c.w.w.l.e.s.s.i.DefaultECMRegisterService (57) [error] - Failed to register info to linkis manager: com.webank.wedatasphere.linkis.common.exception.ErrorException: errCode: 0 ,desc:
 operation failed(操作失败)s！the reason(原因)：SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate) ,ip: VM-160-12-centos ,port: 11132 ,serviceKind: linkis-cg-linkismanager
        at com.webank.wedatasphere.linkis.common.exception.ExceptionManager.generateException(ExceptionManager.java:49) ~[linkis-common-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.rpc.transform.RPCConsumer$$anon$1.toObject(RPCConsumer.scala:66) ~[linkis-rpc-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.rpc.BaseRPCSender$$anonfun$ask$1.apply(BaseRPCSender.scala:85) ~[linkis-rpc-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.rpc.interceptor.BaseRPCInterceptorExchange.invoke(RPCInterceptorExchange.scala:30) ~[linkis-rpc-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.rpc.interceptor.common.CommonRPCInterceptor.intercept(CommonRPCInterceptor.scala:27) ~[linkis-rpc-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.rpc.interceptor.BaseRPCInterceptorChain.handle(RPCInterceptorChain.scala:33) ~[linkis-rpc-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.rpc.interceptor.common.RetryableRPCInterceptor.intercept(RetryableRPCInterceptor.scala:53) ~[linkis-rpc-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.rpc.interceptor.BaseRPCInterceptorChain.handle(RPCInterceptorChain.scala:33) ~[linkis-rpc-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.rpc.interceptor.common.CacheableRPCInterceptor.intercept(CacheableRPCInterceptor.scala:57) ~[linkis-rpc-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.rpc.interceptor.BaseRPCInterceptorChain.handle(RPCInterceptorChain.scala:33) ~[linkis-rpc-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.rpc.interceptor.common.BroadcastRPCInterceptor.intercept(BroadcastRPCInterceptor.scala:72) ~[linkis-rpc-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.rpc.interceptor.BaseRPCInterceptorChain.handle(RPCInterceptorChain.scala:33) ~[linkis-rpc-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.rpc.BaseRPCSender.execute(BaseRPCSender.scala:77) ~[linkis-rpc-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.rpc.BaseRPCSender.ask(BaseRPCSender.scala:81) ~[linkis-rpc-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.ecm.server.service.impl.DefaultECMRegisterService$$anonfun$registerECM$1.apply$mcV$sp(DefaultECMRegisterService.scala:86) ~[linkis-engineconn-manager-server-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.ecm.server.service.impl.DefaultECMRegisterService$$anonfun$registerECM$1.apply(DefaultECMRegisterService.scala:84) ~[linkis-engineconn-manager-server-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.ecm.server.service.impl.DefaultECMRegisterService$$anonfun$registerECM$1.apply(DefaultECMRegisterService.scala:84) ~[linkis-engineconn-manager-server-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:39) [linkis-common-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.ecm.server.service.impl.DefaultECMRegisterService.registerECM(DefaultECMRegisterService.scala:97) [linkis-engineconn-manager-server-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.ecm.server.service.impl.DefaultECMRegisterService.onEvent(DefaultECMRegisterService.scala:71) [linkis-engineconn-manager-server-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.ecm.core.listener.ECMSyncListenerBus.doPostEvent(ECMSyncListenerBus.scala:26) [linkis-engineconn-manager-core-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.ecm.core.listener.ECMSyncListenerBus.doPostEvent(ECMSyncListenerBus.scala:21) [linkis-engineconn-manager-core-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.common.listener.ListenerBus$$anonfun$postToAll$1.apply$mcV$sp(ListenerEventBus.scala:61) [linkis-common-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.common.listener.ListenerBus$$anonfun$postToAll$1.apply(ListenerEventBus.scala:61) [linkis-common-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.common.listener.ListenerBus$$anonfun$postToAll$1.apply(ListenerEventBus.scala:61) [linkis-common-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.common.utils.Utils$.tryCatch(Utils.scala:39) [linkis-common-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.common.listener.ListenerBus$class.postToAll(ListenerEventBus.scala:62) [linkis-common-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.ecm.core.listener.ECMSyncListenerBus.postToAll(ECMSyncListenerBus.scala:21) [linkis-engineconn-manager-core-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.ecm.server.ECMApplicationListener.onApplicationReady(LinkisECMApplication.java:98) [linkis-engineconn-manager-server-1.0.2.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:305) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:190) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:153) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361) [spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:108) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:77) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:330) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at com.webank.wedatasphere.linkis.DataWorkCloudApplication.main(DataWorkCloudApplication.java:108) [linkis-module-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.LinkisBaseServerApp.main(LinkisBaseServerApp.java:48) [linkis-module-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.ecm.server.LinkisECMApplication.main(LinkisECMApplication.java:49) [linkis-engineconn-manager-server-1.0.2.jar:?]

**Comment by juyonychen** [comment]
问题已经解决
