### ISSUE TITLE
DSS1.0 一键安装项目启动出现上传appconn失败

### ISSUE THREAD

**Issue by seelecpt** [WeBankFinTech/DataSphereStudio#437]
查看了QA常见问题，与首次上传资源失败相关，并确认已经有配置了HADOOP相关路径。
在启动dss-framework-project-server的时候，扫描appconn下对应文件夹，并生成zip文件，上传到hdfs，在hdfs出现了org.apache.hadoop.fs.ChecksumException: Checksum ，crc验证不通过。从而导致了启动失败。请问对应的问题该如何处理。

dss-framework-project-server 日志如下：
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-10-24 20:58:11.816 ERROR [main] org.springframework.boot.SpringApplication 837 reportFailure - Application run failed org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'appConnManagerRestfulApi': Invocation of init method failed; nested exception is LinkisException{errCode=100000, desc='errCode: 10905 ,desc: URL /api/rest_j/v1/bml/upload request failed! ResponseBody is {"method":null,"status":1,"message":"error code(错误码): 60050, error message(错误信息): The first upload of the resource failed(首次上传资源失败).","data":{"errorMsg":{"serviceKind":"linkis-ps-publicservice","level":2,"port":9105,"errCode":50073,"ip":"SRVDATAPANEL01","desc":"The commit upload resource task failed(提交上传资源任务失败):errCode: 60050 ,desc: The first upload of the resource failed(首次上传资源失败) ,ip: SRVDATAPANEL01 ,port: 9105 ,serviceKind: linkis-ps-publicservice"}}}. ,ip: SRVDATAPANEL01 ,port: 9002 ,serviceKind: dss-framework-project-server', ip='SRVDATAPANEL01', port=9002, serviceKind='dss-framework-project-server'}
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at com.webank.wedatasphere.linkis.DataWorkCloudApplication.main(DataWorkCloudApplication.java:108) [linkis-module-1.0.2.jar:?]
        at com.webank.wedatasphere.dss.framework.project.server.DSSProjectServerApplication$.main(DSSProjectServerApplication.scala:36) [dss-framework-project-server-1.0.0.jar:?]
        at com.webank.wedatasphere.dss.framework.project.server.DSSProjectServerApplication.main(DSSProjectServerApplication.scala) [dss-framework-project-server-1.0.0.jar:?]
Caused by: com.webank.wedatasphere.dss.common.exception.DSSRuntimeException: errCode: 100000 ,desc: errCode: 10905 ,desc: URL /api/rest_j/v1/bml/upload request failed! ResponseBody is {"method":null,"status":1,"message":"error code(错误码): 60050, error message(错误信息): The first upload of the resource failed(首次上传资源失败).","data":{"errorMsg":{"serviceKind":"linkis-ps-publicservice","level":2,"port":9105,"errCode":50073,"ip":"SRVDATAPANEL01","desc":"The commit upload resource task failed(提交上传资源任务失败):errCode: 60050 ,desc: The first upload of the resource failed(首次上传资源失败) ,ip: SRVDATAPANEL01 ,port: 9105 ,serviceKind: linkis-ps-publicservice"}}}. ,ip: SRVDATAPANEL01 ,port: 9002 ,serviceKind: dss-framework-project-server ,ip: SRVDATAPANEL01 ,port: 9002 ,serviceKind: dss-framework-project-server
        at com.webank.wedatasphere.dss.common.utils.DSSExceptionUtils.lambda$handling$0(DSSExceptionUtils.java:46) ~[dss-common-1.0.0.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_301]
        at com.webank.wedatasphere.dss.framework.appconn.restful.AppConnManagerRestfulApi.init(AppConnManagerRestfulApi.java:57) ~[dss-appconn-framework-1.0.0.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_301]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_301]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_301]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        ... 19 more

linkis-ps-publicservice.out 日志如下：

Caused by: com.webank.wedatasphere.linkis.bml.common.UploadResourceException: errCode: 60050 ,desc: The first upload of the resource failed(首次上传资源失败) ,ip: SRVDATAPANEL01 ,port: 9105 ,serviceKind: linkis-ps-publicservice
        at com.webank.wedatasphere.linkis.bml.common.HdfsResourceHelper.upload(HdfsResourceHelper.java:92) ~[linkis-bmlserver-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.bml.service.impl.ResourceServiceImpl.upload(ResourceServiceImpl.java:87) ~[linkis-bmlserver-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.bml.service.impl.ResourceServiceImpl$$FastClassBySpringCGLIB$$5c37157.invoke(<generated>) ~[linkis-bmlserver-1.0.2.jar:?]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367) ~[spring-tx-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at com.webank.wedatasphere.linkis.bml.service.impl.ResourceServiceImpl$$EnhancerBySpringCGLIB$$d6822f23.upload(<generated>) ~[linkis-bmlserver-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.bml.service.impl.TaskServiceImpl.createUploadTask(TaskServiceImpl.java:77) ~[linkis-bmlserver-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.bml.service.impl.TaskServiceImpl$$FastClassBySpringCGLIB$$4c48a780.invoke(<generated>) ~[linkis-bmlserver-1.0.2.jar:?]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367) ~[spring-tx-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.12.RELEASE.jar:5.2.12.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at com.webank.wedatasphere.linkis.bml.service.impl.TaskServiceImpl$$EnhancerBySpringCGLIB$$57ec733e.createUploadTask(<generated>) ~[linkis-bmlserver-1.0.2.jar:?]
        at com.webank.wedatasphere.linkis.bml.restful.BmlRestfulApi.uploadResource(BmlRestfulApi.java:457) ~[linkis-bmlserver-1.0.2.jar:?]
        ... 95 more
Caused by: org.apache.hadoop.fs.ChecksumException: Checksum error: /apps-data/root/bml/20211024/60eabc23-e329-4058-ae0a-bcdeb24234b1 at 3144704
        at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.readChunk(ChecksumFileSystem.java:254) ~[hadoop-common-2.7.2.jar:?]
        at org.apache.hadoop.fs.FSInputChecker.readChecksumChunk(FSInputChecker.java:276) ~[hadoop-common-2.7.2.jar:?]
        at org.apache.hadoop.fs.FSInputChecker.read1(FSInputChecker.java:228) ~[hadoop-common-2.7.2.jar:?]
        at org.apache.hadoop.fs.FSInputChecker.read(FSInputChecker.java:196) ~[hadoop-common-2.7.2.jar:?]

**Comment by cmdbdu** [comment]
+1

**Comment by HQTB123** [comment]
+1

**Comment by zhangxn8** [comment]
+1

**Comment by zhangxn8** [comment]
> 查看了QA常见问题，与首次上传资源失败相关，并确认已经有配置了HADOOP相关路径。 在启动dss-framework-project-server的时候，扫描appconn下对应文件夹，并生成zip文件，上传到hdfs，在hdfs出现了org.apache.hadoop.fs.ChecksumException: Checksum ，crc验证不通过。从而导致了启动失败。请问对应的问题该如何处理。
> 
> dss-framework-project-server 日志如下： Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. 2021-10-24 20:58:11.816 ERROR [main] org.springframework.boot.SpringApplication 837 reportFailure - Application run failed org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'appConnManagerRestfulApi': Invocation of init method failed; nested exception is LinkisException{errCode=100000, desc='errCode: 10905 ,desc: URL /api/rest_j/v1/bml/upload request failed! ResponseBody is {"method":null,"status":1,"message":"error code(错误码): 60050, error message(错误信息): The first upload of the resource failed(首次上传资源失败).","data":{"errorMsg":{"serviceKind":"linkis-ps-publicservice","level":2,"port":9105,"errCode":50073,"ip":"SRVDATAPANEL01","desc":"The commit upload resource task failed(提交上传资源任务失败):errCode: 60050 ,desc: The first upload of the resource failed(首次上传资源失败) ,ip: SRVDATAPANEL01 ,port: 9105 ,serviceKind: linkis-ps-publicservice"}}}. ,ip: SRVDATAPANEL01 ,port: 9002 ,serviceKind: dss-framework-project-server', ip='SRVDATAPANEL01', port=9002, serviceKind='dss-framework-project-server'} at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE] at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE] at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE] at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE] at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE] at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE] at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE] at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE] at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE] at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE] at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE] at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE] at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE] at com.webank.wedatasphere.linkis.DataWorkCloudApplication.main(DataWorkCloudApplication.java:108) [linkis-module-1.0.2.jar:?] at com.webank.wedatasphere.dss.framework.project.server.DSSProjectServerApplication$.main(DSSProjectServerApplication.scala:36) [dss-framework-project-server-1.0.0.jar:?] at com.webank.wedatasphere.dss.framework.project.server.DSSProjectServerApplication.main(DSSProjectServerApplication.scala) [dss-framework-project-server-1.0.0.jar:?] Caused by: com.webank.wedatasphere.dss.common.exception.DSSRuntimeException: errCode: 100000 ,desc: errCode: 10905 ,desc: URL /api/rest_j/v1/bml/upload request failed! ResponseBody is {"method":null,"status":1,"message":"error code(错误码): 60050, error message(错误信息): The first upload of the resource failed(首次上传资源失败).","data":{"errorMsg":{"serviceKind":"linkis-ps-publicservice","level":2,"port":9105,"errCode":50073,"ip":"SRVDATAPANEL01","desc":"The commit upload resource task failed(提交上传资源任务失败):errCode: 60050 ,desc: The first upload of the resource failed(首次上传资源失败) ,ip: SRVDATAPANEL01 ,port: 9105 ,serviceKind: linkis-ps-publicservice"}}}. ,ip: SRVDATAPANEL01 ,port: 9002 ,serviceKind: dss-framework-project-server ,ip: SRVDATAPANEL01 ,port: 9002 ,serviceKind: dss-framework-project-server at com.webank.wedatasphere.dss.common.utils.DSSExceptionUtils.lambda$handling$0(DSSExceptionUtils.java:46) ~[dss-common-1.0.0.jar:?] at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_301] at com.webank.wedatasphere.dss.framework.appconn.restful.AppConnManagerRestfulApi.init(AppConnManagerRestfulApi.java:57) ~[dss-appconn-framework-1.0.0.jar:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_301] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_301] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_301] at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE] at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE] at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.2.12.RELEASE.jar:5.2.12.RELEASE] ... 19 more
> 
> linkis-ps-publicservice.out 日志如下：
> 
> Caused by: com.webank.wedatasphere.linkis.bml.common.UploadResourceException: errCode: 60050 ,desc: The first upload of the resource failed(首次上传资源失败) ,ip: SRVDATAPANEL01 ,port: 9105 ,serviceKind: linkis-ps-publicservice at com.webank.wedatasphere.linkis.bml.common.HdfsResourceHelper.upload(HdfsResourceHelper.java:92) ~[linkis-bmlserver-1.0.2.jar:?] at com.webank.wedatasphere.linkis.bml.service.impl.ResourceServiceImpl.upload(ResourceServiceImpl.java:87) ~[linkis-bmlserver-1.0.2.jar:?] at com.webank.wedatasphere.linkis.bml.service.impl.ResourceServiceImpl$$FastClassBySpringCGLIB$$5c37157.invoke() ~[linkis-bmlserver-1.0.2.jar:?] at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.12.RELEASE.jar:5.2.12.RELEASE] at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE] at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE] at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367) ~[spring-tx-5.2.12.RELEASE.jar:5.2.12.RELEASE] at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.12.RELEASE.jar:5.2.12.RELEASE] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE] at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE] at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE] at com.webank.wedatasphere.linkis.bml.service.impl.ResourceServiceImpl$$EnhancerBySpringCGLIB$$d6822f23.upload() ~[linkis-bmlserver-1.0.2.jar:?] at com.webank.wedatasphere.linkis.bml.service.impl.TaskServiceImpl.createUploadTask(TaskServiceImpl.java:77) ~[linkis-bmlserver-1.0.2.jar:?] at com.webank.wedatasphere.linkis.bml.service.impl.TaskServiceImpl$$FastClassBySpringCGLIB$$4c48a780.invoke() ~[linkis-bmlserver-1.0.2.jar:?] at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.12.RELEASE.jar:5.2.12.RELEASE] at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE] at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE] at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367) ~[spring-tx-5.2.12.RELEASE.jar:5.2.12.RELEASE] at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.12.RELEASE.jar:5.2.12.RELEASE] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE] at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE] at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE] at com.webank.wedatasphere.linkis.bml.service.impl.TaskServiceImpl$$EnhancerBySpringCGLIB$$57ec733e.createUploadTask() ~[linkis-bmlserver-1.0.2.jar:?] at com.webank.wedatasphere.linkis.bml.restful.BmlRestfulApi.uploadResource(BmlRestfulApi.java:457) ~[linkis-bmlserver-1.0.2.jar:?] ... 95 more Caused by: org.apache.hadoop.fs.ChecksumException: Checksum error: /apps-data/root/bml/20211024/60eabc23-e329-4058-ae0a-bcdeb24234b1 at 3144704 at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.readChunk(ChecksumFileSystem.java:254) ~[hadoop-common-2.7.2.jar:?] at org.apache.hadoop.fs.FSInputChecker.readChecksumChunk(FSInputChecker.java:276) ~[hadoop-common-2.7.2.jar:?] at org.apache.hadoop.fs.FSInputChecker.read1(FSInputChecker.java:228) ~[hadoop-common-2.7.2.jar:?] at org.apache.hadoop.fs.FSInputChecker.read(FSInputChecker.java:196) ~[hadoop-common-2.7.2.jar:?]

你这个问题解决了吗

**Comment by wangcomeoffit** [comment]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-03-20 14:34:09.733 [ERROR] [main                                    ] o.s.b.SpringApplication (834) [reportFailure] - Application run failed org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'appConnManagerRestfulApi': Invocation of init method failed; nested exception is LinkisException{errCode=100000, desc='HttpClientResultException: errCode: 10905 ,desc: URL /api/rest_j/v1/bml/updateVersion request failed! ResponseBody is {"method":null,"status":1,"message":"error code(错误码): 78361, error message(错误信息): resourceId: eeef194c-af6c-4152-8923-caf1c35ca230 is Null, illegal, or deleted!.","data":{"errorMsg":{"serviceKind":"linkis-ps-publicservice","level":2,"port":9105,"errCode":78361,"ip":"hdp01","desc":"resourceId: eeef194c-af6c-4152-8923-caf1c35ca230 is Null, illegal, or deleted!"}}}. errCode: 10905 ,desc: URL /api/rest_j/v1/bml/updateVersion request failed! ResponseBody is {"method":null,"status":1,"message":"error code(错误码): 78361, error message(错误信息): resourceId: eeef194c-af6c-4152-8923-caf1c35ca230 is Null, illegal, or deleted!.","data":{"errorMsg":{"serviceKind":"linkis-ps-publicservice","level":2,"port":9105,"errCode":78361,"ip":"hdp01","desc":"resourceId: eeef194c-af6c-4152-8923-caf1c35ca230 is Null, illegal, or deleted!"}}}. ,ip: hdp01 ,port: 9002 ,serviceKind: dss-framework-project-server ,ip: hdp01 ,port: 9002 ,serviceKind: dss-framework-project-server', ip='hdp01', port=9002, serviceKind='dss-framework-project-server'}

**Comment by chen-ke-lei** [comment]
> 

你解决了吗

**Comment by chen-ke-lei** [comment]
> Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. 2023-03-20 14:34:09.733 [ERROR] [main ] o.s.b.SpringApplication (834) [reportFailure] - Application run failed org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'appConnManagerRestfulApi': Invocation of init method failed; nested exception is LinkisException{errCode=100000, desc='HttpClientResultException: errCode: 10905 ,desc: URL /api/rest_j/v1/bml/updateVersion request failed! ResponseBody is {"method":null,"status":1,"message":"error code(错误码): 78361, error message(错误信息): resourceId: eeef194c-af6c-4152-8923-caf1c35ca230 is Null, illegal, or deleted!.","data":{"errorMsg":{"serviceKind":"linkis-ps-publicservice","level":2,"port":9105,"errCode":78361,"ip":"hdp01","desc":"resourceId: eeef194c-af6c-4152-8923-caf1c35ca230 is Null, illegal, or deleted!"}}}. errCode: 10905 ,desc: URL /api/rest_j/v1/bml/updateVersion request failed! ResponseBody is {"method":null,"status":1,"message":"error code(错误码): 78361, error message(错误信息): resourceId: eeef194c-af6c-4152-8923-caf1c35ca230 is Null, illegal, or deleted!.","data":{"errorMsg":{"serviceKind":"linkis-ps-publicservice","level":2,"port":9105,"errCode":78361,"ip":"hdp01","desc":"resourceId: eeef194c-af6c-4152-8923-caf1c35ca230 is Null, illegal, or deleted!"}}}. ,ip: hdp01 ,port: 9002 ,serviceKind: dss-framework-project-server ,ip: hdp01 ,port: 9002 ,serviceKind: dss-framework-project-server', ip='hdp01', port=9002, serviceKind='dss-framework-project-server'}

你解决了吗

**Comment by 303470934** [comment]
这问题有没有解决的大佬回复下？

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
持续为DataSphereStudio开源贡献力量

**Comment by luyuanshao** [comment]
有人解决吗？
