### ISSUE TITLE
dss1.0  visualis - display 增加辅助图形报错

### ISSUE THREAD

**Issue by xiaoxd** [WeBankFinTech/DataSphereStudio#454]
报错信息：
`
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 3 path $[0]
	at com.google.gson.Gson.fromJson(Gson.java:975)
	at com.google.gson.Gson.fromJson(Gson.java:928)
	at com.google.gson.Gson.fromJson(Gson.java:877)
	at com.google.gson.Gson.fromJson(Gson.java:848)
	at pers.xiaoxd.druidsample.DruidSampleApplication.main(DruidSampleApplication.java:28)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 3 path $[0]
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:349)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:172)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:963)
	... 4 more
`

示例代码：
`
        Gson gson = new Gson();
        Map<String, MemDisplaySlideWidgetCreate> obj = new LinkedHashMap<>();
        obj = gson.fromJson("[{\"widgetId\":1,\"name\":\"企业规模分布饼图\",\"type\":1,\"params\":\"{\\\"width\\\":460,\\\"height\\\":250,\\\"positionX\\\":16,\\\"positionY\\\":16,\\\"backgroundColor\\\":[255,255,255,0],\\\"borderColor\\\":[0,0,0],\\\"borderWidth\\\":null,\\\"borderStyle\\\":\\\"solid\\\",\\\"borderRadius\\\":null,\\\"polling\\\":\\\"false\\\",\\\"frequency\\\":60}\",\"index\":1,\"displaySlideId\":3}]", obj.getClass());

public class MemDisplaySlideWidgetCreate {

    private Long id;

    private String name;

    private Long displaySlideId;

    private Long widgetId;

    private Short type;

    private Short subType;

    private Integer index = 0;

    private String params;

    private List<Long> roleIds;
}
`

报错的代码：
\DataSphereStudio\plugins\linkis\dss-gateway-support\src\main\scala\com\webank\wedatasphere\linkis\gateway\parser\DSSGatewayParser.scala
getServiceNameFromLabel方法
val json = BDPJettyServerHelper.gson.fromJson(body, classOf[java.util.Map[String, Object]])

**Comment by wushengyeyouya** [comment]
Can you give us more information about this usage?

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
持续为DataSphereStudio开源贡献力量
