### ISSUE TITLE
Schedulis单独部署 执行工作流报错

### ISSUE THREAD

**Issue by LEOPROGRAM** [WeBankFinTech/DataSphereStudio#472]
06-01-2022 10:02:34 CST sql_3819 INFO - Starting job sql_3819 at 1641434554021
06-01-2022 10:02:34 CST sql_3819 INFO - job JVM args: -Dazkaban.flowid=Scheduler -Dazkaban.execid=79 -Dazkaban.jobid=sql_3819
06-01-2022 10:02:34 CST sql_3819 INFO - Building linkis job executor. 
06-01-2022 10:02:34 CST sql_3819 INFO - Start to execute job
06-01-2022 10:02:34 CST sql_3819 INFO - ******   Job properties   ******
06-01-2022 10:02:34 CST sql_3819 INFO - - Note : value is masked if property name ends with '_X'.
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.url=http://localhost:8081
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.job.id=sql_3819
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.job.attempt=0
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.flow.start.year=2022
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.link.execution.url=http://localhost:8081/executor?execid=79
06-01-2022 10:02:34 CST sql_3819 INFO - linkis.version=1.0.0
06-01-2022 10:02:34 CST sql_3819 INFO - type=linkis
06-01-2022 10:02:34 CST sql_3819 INFO - job.datachecker.jdo.option.name="job"
06-01-2022 10:02:34 CST sql_3819 INFO - bdp.datachecker.jdo.option.name="bdp"
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.flow.projectversion=1
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.flow.start.minute=02
06-01-2022 10:02:34 CST sql_3819 INFO - plugin.dir=/appcom/Install/AzkabanInstall/schedulis_0.6.1_exec/plugins/jobtypes/linkis
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.flow.execid=79
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.link.workflow.url=http://localhost:8081/manager?project=Scheduler&flow=Scheduler
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.job.attachment.file=/appcom/Install/AzkabanInstall/schedulis_0.6.1_exec/executions/79/Scheduler/Scheduler/jobs/sql_3819/_job.79.sql_3819.attach
06-01-2022 10:02:34 CST sql_3819 INFO - msg.eventchecker.jdo.option.name="msg"
06-01-2022 10:02:34 CST sql_3819 INFO - jvm.args=-Dazkaban.flowid=Scheduler -Dazkaban.execid=79 -Dazkaban.jobid=sql_3819
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.flow.uuid=551d3c1b-63b9-4755-8ca0-ea962a6524da
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.link.jobexec.url=http://localhost:8081/executor?execid=79&job=sql_3819
06-01-2022 10:02:34 CST sql_3819 INFO - job.datachecker.jdo.option.username=root
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.memory.check=true
06-01-2022 10:02:34 CST sql_3819 INFO - msg.eventchecker.jdo.option.password=cm9vdA==
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.flow.start.timestamp=2022-01-06T10:02:33.993+08:00
06-01-2022 10:02:34 CST sql_3819 INFO - linkistype=linkis.spark.sql
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.link.attempt.url=http://localhost:8081/executor?execid=79&job=sql_3819&attempt=0
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.flow.start.milliseconds=993
06-01-2022 10:02:34 CST sql_3819 INFO - wds.linkis.flow.contextID={"type":"HAWorkFlowContextID","value":"{/"instance/":null,/"backupInstance/":null,/"user/":/"dss/",/"workspace/":/"bdapWorkspace/",/"project/":/"Scheduler/",/"flow/":/"Scheduler/",/"contextId/":/"8-8--cs_1_devcs_1_dev31/",/"version/":/"v000001/",/"env/":/"BDAP_DEV/"}"}
06-01-2022 10:02:34 CST sql_3819 INFO - flow.dir=/appcom/Install/AzkabanInstall/schedulis_0.6.1_exec/executions/79
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.flow.submituser=superadmin
06-01-2022 10:02:34 CST sql_3819 INFO - labels={"route":"dev"}
06-01-2022 10:02:34 CST sql_3819 INFO - job.datachecker.jdo.option.url=jdbc:mysql://192.168.217.101:3306/hive?useUnicode=true&characterEncoding=UTF-8
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.flow.projectname=Scheduler
06-01-2022 10:02:34 CST sql_3819 INFO - wds.linkis.gateway.url=http://192.168.217.100:9001
06-01-2022 10:02:34 CST sql_3819 INFO - msg.eventchecker.jdo.option.url=jdbc:mysql://192.168.217.101:3306/schedulis?useUnicode=true&characterEncoding=UTF-8
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.flow.start.month=01
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.native.lib=/appcom/Install/AzkabanInstall/schedulis_0.6.1_exec/lib
06-01-2022 10:02:34 CST sql_3819 INFO - bdp.datachecker.jdo.option.username=[#DATACHECKER_BDP_USER]
06-01-2022 10:02:34 CST sql_3819 INFO - msg.eventchecker.jdo.option.username=root
06-01-2022 10:02:34 CST sql_3819 INFO - spark.home=/usr/hdp/2.6.2.14-5/spark2
06-01-2022 10:02:34 CST sql_3819 INFO - hive.home=/usr/hdp/2.6.2.14-5/hive
06-01-2022 10:02:34 CST sql_3819 INFO - wds.linkis.flow.job.creator=scheduler
06-01-2022 10:02:34 CST sql_3819 INFO - hadoop.home=/usr/hdp/2.6.2.14-5/hadoop
06-01-2022 10:02:34 CST sql_3819 INFO - flow.variable.user.to.proxy=dss
06-01-2022 10:02:34 CST sql_3819 INFO - bdp.datachecker.jdo.option.password=[#DATACHECKER_BDP_PWD]
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.flow.start.hour=10
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.job.log.file=/appcom/Install/AzkabanInstall/schedulis_0.6.1_exec/executions/79/Scheduler/Scheduler/jobs/sql_3819/_job.79.sql_3819.log
06-01-2022 10:02:34 CST sql_3819 INFO - user.to.proxy=dss
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.flow.flowid=Scheduler
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.flow.start.day=06
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.job.outnodes=Scheduler
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.link.job.url=http://localhost:8081/manager?project=Scheduler&flow=Scheduler&job=sql_3819
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.flow.projectlastchangedby=superadmin
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.job.innodes=
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.flow.start.timezone=Asia/Shanghai
06-01-2022 10:02:34 CST sql_3819 INFO - resources=[{"fileName":"1e5719d4-8822-4d2b-86b0-76c01fdf8907.sql","resourceId":"09267a9a-351e-4bfb-a545-affce313dee5","version":"v000001"}]
06-01-2022 10:02:34 CST sql_3819 INFO - execute.as.user=true
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.flow.projectid=5
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.flow.start.second=33
06-01-2022 10:02:34 CST sql_3819 INFO - command={"script":"1e5719d4-8822-4d2b-86b0-76c01fdf8907.sql"}
06-01-2022 10:02:34 CST sql_3819 INFO - working.dir=/appcom/Install/AzkabanInstall/schedulis_0.6.1_exec/executions/79/Scheduler/Scheduler/jobs/sql_3819
06-01-2022 10:02:34 CST sql_3819 INFO - job.datachecker.jdo.option.password=cm9vdA==
06-01-2022 10:02:34 CST sql_3819 INFO - wds.linkis.client.flow.author.user.token=WS-AUTH
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.job.metadata.file=_job.79.sql_3819.meta
06-01-2022 10:02:34 CST sql_3819 INFO - azkaban.flow.projectlastchangeddate=1641434057442
06-01-2022 10:02:34 CST sql_3819 INFO - bdp.datachecker.jdo.option.url=jdbc:mysql://[#DATACHECKER_BDP_IP]:[#DATACHECKER_BDP_PORT]/[#DATACHECKER_BDP_DBNAME]?useUnicode=true&characterEncoding=UTF-8
06-01-2022 10:02:34 CST sql_3819 INFO - ****** End Job properties  ******
06-01-2022 10:02:34 CST sql_3819 ERROR - Job run failed!
java.lang.NoClassDefFoundError: Could not initialize class com.webank.wedatasphere.dss.plugins.azkaban.linkis.jobtype.job.JobBuilder
	at com.webank.wedatasphere.dss.plugins.azkaban.linkis.jobtype.AzkabanDssJobType.run(AzkabanDssJobType.java:149) ~[?:?]
	at azkaban.execapp.JobRunner.runJob(JobRunner.java:836) [azkaban-exec-server-0.6.1.jar:?]
	at azkaban.execapp.JobRunner.jobRunHandle(JobRunner.java:1037) [azkaban-exec-server-0.6.1.jar:?]
	at azkaban.execapp.JobRunner.doRun(JobRunner.java:591) [azkaban-exec-server-0.6.1.jar:?]
	at azkaban.execapp.JobRunner.run(JobRunner.java:548) [azkaban-exec-server-0.6.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
06-01-2022 10:02:34 CST sql_3819 ERROR - Could not initialize class com.webank.wedatasphere.dss.plugins.azkaban.linkis.jobtype.job.JobBuilder cause: null
06-01-2022 10:02:34 CST sql_3819 INFO - Finishing job sql_3819 at 1641434554039 with status FAILED

**Comment by LEOPROGRAM** [comment]
[https://github.com/WeBankFinTech/Schedulis/issues/79](url)

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
持续为DataSphereStudio开源贡献力量
