### ISSUE TITLE
[Bug] 【dss1.0.1】版本: 在工作流拖拽了jdbc，双击该jdbc节点，页面无法正常打开

### ISSUE THREAD

**Issue by windwhisper-i** [WeBankFinTech/DataSphereStudio#557]
### Search before asking

- [ ] I searched the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar issues.

### DSS Component

dss-web/dss-workflow

### What happened + What you expected to happen

![image](https://user-images.githubusercontent.com/73170854/161007868-47a354d7-49cf-4fdf-9fdb-449a7bbb412e.png)

### Relevent platform

centos7 
dss1.0.1
linkis1.0.3

### Reproduction script

TypeError: Cannot read properties of undefined (reading 'class')
    at app.71cbbca6.js:1:2219710
    at s.jt [as _l] (chunk-vendors.f7460978.js:74:16912)
    at s.t (app.71cbbca6.js:1:2219331)
    at s.e._render (chunk-vendors.f7460978.js:74:23733)
    at s.i (chunk-vendors.f7460978.js:74:27824)
    at ni.get (chunk-vendors.f7460978.js:74:30684)
    at ni.run (chunk-vendors.f7460978.js:74:31417)
    at Zn (chunk-vendors.f7460978.js:74:29624)
    at Array.<anonymous> (chunk-vendors.f7460978.js:74:12761)
    at lt (chunk-vendors.f7460978.js:74:12156)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wushengyeyouya** [comment]
This bug is fixed.
