### ISSUE TITLE
[Bug] Failed  to async(iZbp14j2amyqhhwlqedv5kZ:9101_62) createEngine, can Retry true org.apache.linkis.common.exception.LinkisRetryException: errCode: 30002 ,desc:  The em of labels{userCreator=root-IDE, codeType=shell, engineType=shell-1} not found ,ip: iZbp14j2amyqhhwlqedv5kZ ,port: 9101 ,serviceKind: linkis-cg-linkismanager

### ISSUE THREAD

**Issue by gongzh021** [WeBankFinTech/DataSphereStudio#561]
### Search before asking

- [X] I searched the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar issues.

### DSS Component

dss-commons

### What happened + What you expected to happen

在线寻求大佬们的帮助，前端执行SQL语句或shell脚本，报错如下：

2022-04-08 20:35:52.067 [INFO ] [AskEngineService-Thread-125             ] o.a.l.m.a.s.e.DefaultEngineCreateService (41) [info] - Start to create Engine for request: EngineCreateRequest{labels={userCreator=root-IDE, codeType=shell, engineType=shell-1}, timeOut=660000, user='root', createService='dssmark_id: mark_3', description='null'}.
2022-04-08 20:35:52.079 [INFO ] [AskEngineService-Thread-126             ] o.a.l.m.a.s.e.DefaultEngineAskEngineService (123) [apply] - Failed  to async(iZbp14j2amyqhhwlqedv5kZ:9101_62) createEngine, can Retry true org.apache.linkis.common.exception.LinkisRetryException: errCode: 30002 ,desc:  The em of labels{userCreator=root-IDE, codeType=shell, engineType=shell-1} not found ,ip: iZbp14j2amyqhhwlqedv5kZ ,port: 9101 ,serviceKind: linkis-cg-linkismanager
        at org.apache.linkis.manager.am.service.engine.DefaultEngineCreateService.createEngine(DefaultEngineCreateService.scala:177) ~[linkis-application-manager-1.0.3.jar:1.0.3]
        at org.apache.linkis.manager.am.service.engine.DefaultEngineAskEngineService$$anonfun$3.apply(DefaultEngineAskEngineService.scala:94) ~[linkis-application-manager-1.0.3.jar:1.0.3]
        at org.apache.linkis.manager.am.service.engine.DefaultEngineAskEngineService$$anonfun$3.apply(DefaultEngineAskEngineService.scala:84) ~[linkis-application-manager-1.0.3.jar:1.0.3]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.12.jar:?]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.12.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

2022-04-08 20:35:52.910 [INFO ] [Linkis-Default-Scheduler-Thread-17      ] o.a.l.m.a.s.m.NodeHeartbeatMonitor (41) [info] - Start to check the health of the node
2022-04-08 20:35:52.916 [INFO ] [Linkis-Default-Scheduler-Thread-17      ] o.a.l.m.a.s.m.NodeHeartbeatMonitor (41) [info] - Finished to check the health of the node
2022-04-08 20:36:07.642 [INFO ] [RpcMessageScheduler-ThreadPool-223      ] o.a.l.m.a.s.h.AMHeartbeatService (41) [info] - Am deal nodeHeartbeatMsg NodeHeartbeatMsg{status=Running, serviceInstance=ServiceInstance(linkis-cg-engineconnmanager, iZbp14j2amyqhhwlqedv5kZ:9102)}
2022-04-08 20:36:07.648 [WARN ] [RpcMessageScheduler-ThreadPool-223      ] o.a.l.m.p.i.DefaultNodeMetricManagerPersistence (85) [addOrupdateNodeMetrics] - The request of update node metrics was ignored, because the node iZbp14j2amyqhhwlqedv5kZ:9102 is not exist.
2022-04-08 20:36:37.641 [INFO ] [RpcMessageScheduler-ThreadPool-224      ] o.a.l.m.a.s.h.AMHeartbeatService (41) [info] - Am deal nodeHeartbeatMsg NodeHeartbeatMsg{status=Running, serviceInstance=ServiceInstance(linkis-cg-engineconnmanager, iZbp14j2amyqhhwlqedv5kZ:9102)}
2022-04-08 20:36:37.647 [WARN ] [RpcMessageScheduler-ThreadPool-224      ] o.a.l.m.p.i.DefaultNodeMetricManagerPersistence (85) [addOrupdateNodeMetrics] - The request of update node metrics was ignored, because the node iZbp14j2amyqhhwlqedv5kZ:9102 is not exist.
2022-04-08 20:37:07.642 [INFO ] [RpcMessageScheduler-ThreadPool-225      ] o.a.l.m.a.s.h.AMHeartbeatService (41) [info] - Am deal nodeHeartbeatMsg NodeHeartbeatMsg{status=Running, serviceInstance=ServiceInstance(linkis-cg-engineconnmanager, iZbp14j2amyqhhwlqedv5kZ:9102)}
2022-04-08 20:37:07.648 [WARN ] [RpcMessageScheduler-ThreadPool-225      ] o.a.l.m.p.i.DefaultNodeMetricManagerPersistence (85) [addOrupdateNodeMetrics] - The request of update node metrics was ignored, because the node iZbp14j2amyqhhwlqedv5kZ:9102 is not exist.

### Relevent platform

null

### Reproduction script

null

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wushengyeyouya** [comment]
Please submit this issue to Linkis.

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
持续为DataSphereStudio开源贡献力量
