### ISSUE TITLE
"dss-framework-orchestrator-server " Components cannot be started

### ISSUE THREAD

**Issue by myamor163** [WeBankFinTech/DataSphereStudio#576]
Startup logs:

2022-04-30 23:21:45.326 ERROR [main] org.springframework.boot.SpringApplication 837 reportFailure - Application run failed org.springfr
amework.beans.factory.BeanCreationException: Error creating bean with name 'orchestratorLoaderUtils': Lookup method resolution failed; 
nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.webank.wedatasphere.dss.orchestrator.loader.utils.
OrchestratorLoaderUtils] from ClassLoader [sun.misc.Launcher$AppClassLoader@13b6d03]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAn
notationBeanPostProcessor.java:289) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(Abs
tractAutowireCapableBeanFactory.java:1290) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanF
actory.java:1205) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory
.java:556) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.j
ava:516) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-bean
s-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~
[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.15.
RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.15.RE
LEASE.jar:5.2.15.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.jav
a:897) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.ja
va:879) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context
-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.j
ava:143) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE
]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.3.2.RELEASE.jar:2.3.2.R
ELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
        at org.apache.linkis.DataWorkCloudApplication.main(DataWorkCloudApplication.java:111) [linkis-module-1.0.3.jar:1.0.3]
        at com.webank.wedatasphere.dss.orchestrator.server.DSSOrchestratorServerApplication$.main(DSSOrchestratorServerApplication.scal
a:37) [dss-framework-orchestrator-server-1.0.1.jar:?]
        at com.webank.wedatasphere.dss.orchestrator.server.DSSOrchestratorServerApplication.main(DSSOrchestratorServerApplication.scala
) [dss-framework-orchestrator-server-1.0.1.jar:?]
Caused by: java.lang.IllegalStateException: Failed to introspect Class [com.webank.wedatasphere.dss.orchestrator.loader.utils.Orchestra
torLoaderUtils] from ClassLoader [sun.misc.Launcher$AppClassLoader@13b6d03]
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481) ~[spring-core-5.2.15.RELEASE.jar:5.2.1
5.RELEASE]
        at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:321) ~[spring-core-5.2.15.RELEASE.jar:5.2.1
5.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAn
notationBeanPostProcessor.java:267) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        ... 19 more
Caused by: java.lang.NoClassDefFoundError: javafx/util/Pair
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_222-ea]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_222-ea]
        at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[?:1.8.0_222-ea]
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463) ~[spring-core-5.2.15.RELEASE.jar:5.2.1
5.RELEASE]
        at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:321) ~[spring-core-5.2.15.RELEASE.jar:5.2.1
5.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAn
notationBeanPostProcessor.java:267) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        ... 19 more
Caused by: java.lang.ClassNotFoundException: javafx.util.Pair
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_222-ea]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222-ea]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_222-ea]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222-ea]
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_222-ea]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_222-ea]
        at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[?:1.8.0_222-ea]
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463) ~[spring-core-5.2.15.RELEASE.jar:5.2.1
5.RELEASE]
--More--(98%)

**Comment by brokge** [comment]
openjdk 下 javafx.util.Pair.  缺失导致的问题。
可以下载  jfxrt.jar 文件，放到  `install/lib/dss-framework/dss-framework-orchestrator-server`目录下，重新启动试试

**Comment by YinDonglai** [comment]
提供最新版DataSphereStudio全家桶安装服务。
包括（DataSphereStudio, Linkis, Exchangeis(Datax, Sqoop), Scriptis, Streamis(Flink), Visualis, DolphinScheduler)
1. 另外包含 元数据，数据安全，数据质量，数据血缘。（这些都是DataSphereStudio不自带的服务）
2. 包含hadoop集群搭建（hive, spark, flink, kafak, kylin）
3. 提供上述所有系统二次定制开发服务
4. 提供系统搭建运维疑难问题解决
![本人微信](https://site-css-test.oss-cn-hangzhou.aliyuncs.com/681723451208_.pic.jpg?x-oss-process=image/resize,w_500,h_300 "扫描二维码添加微信")
持续为DataSphereStudio开源贡献力量
