### ISSUE TITLE
Failed to create projects

### ISSUE THREAD

**Issue by RainFlying** [WeBankFinTech/DataSphereStudio#62]
The error message is:

error code(错误码): 90002, error message(错误信息): add scheduler project failederrCode: 90019 ,desc: Connection reset ,ip: DataSphere-web1 ,port: 9004 ,serviceKind: dss-server.

Checked dss server log, found the following error messages:
```
2019-12-26 11:11:32.099 [ERROR] [qtp585718112-25                         ] c.w.w.d.a.s.a.s.AzkabanSecurityService (80) [login] - 获取session失败: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210) ~[?:1.8.0_232]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_232]
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[httpcore-4.4.7.jar:4.4.7]
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153) ~[httpcore-4.4.7.jar:4.4.7]
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282) ~[httpcore-4.4.7.jar:4.4.7]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138) ~[httpclient-4.5.4.jar:4.5.4]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[httpclient-4.5.4.jar:4.5.4]
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[httpcore-4.4.7.jar:4.4.7]
```
```
2019-12-26 11:11:32.106 [ERROR] [qtp585718112-25                         ] c.w.w.d.s.s.i.DWSProjectServiceImpl (166) [createSchedulerProject] - add scheduler project failed, com.webank.wedatasphere.dss.appjoint.exception.AppJointErrorException: errCode: 90019 ,desc: Connection reset ,ip: DataSphere-web1 ,port: 9004 ,serviceKind: dss-server
        at com.webank.wedatasphere.dss.appjoint.scheduler.azkaban.service.AzkabanSecurityService.login(AzkabanSecurityService.java:81) ~[?:?]
        at com.webank.wedatasphere.dss.server.function.FunctionInvoker.projectServiceAddFunction(FunctionInvoker.java:76) ~[dss-server-0.6.0.jar:?]
        at com.webank.wedatasphere.dss.server.service.impl.DWSProjectServiceImpl.createSchedulerProject(DWSProjectServiceImpl.java:161) [dss-server-0.6.0.jar:?]
        at com.webank.wedatasphere.dss.server.service.impl.DWSProjectServiceImpl.addProject(DWSProjectServiceImpl.java:109) [dss-server-0.6.0.jar:?]
        at com.webank.wedatasphere.dss.server.service.impl.DWSProjectServiceImpl$$FastClassBySpringCGLIB$$fe55cc96.invoke(<generated>) [dss-server-0.6.0.jar:?]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-5.0.7.RELEASE.jar:5.0.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) [spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
```

Azkaban is running.

```
tcp        0      0 0.0.0.0:12321           0.0.0.0:*               LISTEN      4789/java
tcp        0      0 0.0.0.0:5005            0.0.0.0:*               LISTEN      4789/java
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      4789/java
```

**Comment by wushengyeyouya** [comment]
Please see: https://github.com/WeBankFinTech/DataSphereStudio/blob/master/docs/zh_CN/ch1/DSS%E5%AE%89%E8%A3%85%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%88%97%E8%A1%A8.md#1-%E5%88%9B%E5%BB%BA%E5%B7%A5%E7%A8%8B%E6%8F%90%E7%A4%BA%E7%94%A8%E6%88%B7token%E4%B8%BA%E7%A9%BA

**Comment by RainFlying** [comment]
> Please see: https://github.com/WeBankFinTech/DataSphereStudio/blob/master/docs/zh_CN/ch1/DSS%E5%AE%89%E8%A3%85%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%88%97%E8%A1%A8.md#1-%E5%88%9B%E5%BB%BA%E5%B7%A5%E7%A8%8B%E6%8F%90%E7%A4%BA%E7%94%A8%E6%88%B7token%E4%B8%BA%E7%A9%BA

Different issues.
I've checked the URL earlier,  couldn't find my issue.
The content of the related file is

```
[hadoop@DataSphere-web1 ~]$ cat dss/dss-server/conf/token.properties
#${userName}=${password}
hadoop=hadoop
```

The error messages showed connection reset, not token empty.

**Comment by wushengyeyouya** [comment]
Can Azkaban login normally?

**Comment by RainFlying** [comment]
> Can Azkaban login normally?

Logged in with azkaban user with no issue.

<img width="1476" alt="Screenshot 2019-12-26 11 52 27" src="https://user-images.githubusercontent.com/507678/71456829-486fea00-27d6-11ea-8640-ad2cce77de0f.png">

**Comment by wushengyeyouya** [comment]
Please see the table dss_application in your DSS database, Is the url of schedulis correct?

**Comment by RainFlying** [comment]
> Please see the table dss_application in your DSS database, Is the url of schedulis correct?

```
|  3 | schedulis | http://10.1.128.108:8091 |                 0 |     1 | NULL          |                      0 | http://10.1.128.108:8091/manager?project=${projectName}      | NULL         |         1 | http://10.1.128.108:8091/homepage
```

```
[hadoop@DataSphere-web1 ~]$ curl http://10.1.128.108:8091
curl: (56) Recv failure: Connection reset by peer
[hadoop@DataSphere-web1 ~]$ lsof -i :8091
COMMAND  PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
java    3497 hadoop    4u  IPv4  25558      0t0  TCP *:jamlink (LISTEN)
```

Got connection reset error message.

**Comment by wushengyeyouya** [comment]
These urls must be same with the real azkaban url you started.
e.g: Please update this record, and set to:
```
|  3 | schedulis | http://156.250.1.48:8081 |                 0 |     1 | NULL          |                      0 | http://156.250.1.48:8081/manager?project=${projectName}      | NULL         |         1 | http://156.250.1.48:8081/homepage
```

**Comment by RainFlying** [comment]
> These urls must be same with the real azkaban url you started.
> e.g: Please update this record, and set to:
> 
> ```
> |  3 | schedulis | http://156.250.1.48:8081 |                 0 |     1 | NULL          |                      0 | http://156.250.1.48:8081/manager?project=${projectName}      | NULL         |         1 | http://156.250.1.48:8081/homepage
> ```

Thanks.
After updating the url in the dss_application table, the connection reset error was gone. However, I found a new error when creating projects in the dashboard.

error code(错误码): 90002, error message(错误信息): add scheduler project failederrCode: 90019 ,desc: errCode: 90041 ,desc: Get azkaban session is null : { "error" : "Incorrect Login. Username/Password not found." } ,ip: DataSphere-web1 ,port: 9004 ,serviceKind: dss-server ,ip: DataSphere-web1 ,port: 9004 ,serviceKind: dss-server.

Tried adding azkaban user to de token.properties, didn't work.

```
[hadoop@DataSphere-web1 conf]$ cat token.properties
#${userName}=${password}
hadoop=hadoop
azkaban=azkaban
```

**Comment by wushengyeyouya** [comment]
```Incorrect Login. Username/Password not found.```
Seems like the azkaban doesn't have the user you logged in DSS.
Try to add it in azkaban user xml.

**Comment by RainFlying** [comment]
> `Incorrect Login. Username/Password not found.`
> Seems like the azkaban doesn't have the user you logged in DSS.
> Try to add it in azkaban user xml.

Added the dss user to user xml, created a project successfully.
Thanks.
