### ISSUE TITLE
[Bug] java.lang.ClassNotFoundException: org.apache.linkis.common.utils.Logging$class

### ISSUE THREAD

**Issue by liaotian1005** [WeBankFinTech/DataSphereStudio#929]
### Search before asking

- [X] I searched the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar issues.

### DSS Component

dss-commons, dss-appconn, dss-framework, dss-orchestrator, dss-standard, dss-plugins, dss-apps/dss-apiservice, dss-web/dss-scriptis, dss-web/dss-workflow, dss-web/workspace, dss-web/dss-apiservice, dss-web/framework

### What happened + What you expected to happen

我编译了linkis 1.1.1.然后编译了dss.启动的时候报错
Caused by: java.lang.ClassNotFoundException: org.apache.linkis.common.utils.Logging$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_221]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_221]
	at org.apache.linkis.rpc.RPCReceiveRestful.<init>(RPCReceiveRestful.scala:37) ~[linkis-rpc-1.1.1.jar:1.1.1]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_221]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_221]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1315) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	... 18 more
在dss中org.apache.linkis.common.utils.Logging是一个抽象类，编译后不会有Logging$class这个文件

### Relevent platform

dss1.1.1编译后无法启动

### Reproduction script

sbin/dss-daemon.sh start dss-apiservice-serve

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by liaotian1005** [comment]
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.linkis.common.utils.Logging.$init$(Lorg/apache/linkis/common/utils/Logging;)V
	at com.webank.wedatasphere.dss.apiservice.DSSApiServiceServerApplication$.<init>(DSSApiServiceServerApplication.scala:24)
	at com.webank.wedatasphere.dss.apiservice.DSSApiServiceServerApplication$.<clinit>(DSSApiServiceServerApplication.scala)
	at com.webank.wedatasphere.dss.apiservice.DSSApiServiceServerApplication.main(DSSApiServiceServerApplication.scala)

**Comment by liaotian1005** [comment]
linkis 1.1.1 
dds master

**Comment by liaotian1005** [comment]
mvn clean scala:compile  package install
